# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:33:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, constr


class FoodConverseGetResponse(BaseModel):
    answerText: constr(min_length=1)
    media: List[Dict[str, Any]]


class FieldItem(BaseModel):
    name: constr(min_length=1)


class Suggests(BaseModel):
    field_: List[FieldItem] = Field(..., alias='_', min_length=0)


class FoodConverseSuggestGetResponse(BaseModel):
    suggests: Suggests
    words: List[Dict[str, Any]]


class CustomFood(BaseModel):
    id: int
    imageUrl: constr(min_length=1)
    price: float
    servings: float
    title: constr(min_length=1)


class FoodCustomFoodsSearchGetResponse(BaseModel):
    customFoods: List[CustomFood] = Field(..., min_length=0)
    number: int
    offset: int
    type: constr(min_length=1)


class Annotation(BaseModel):
    annotation: constr(min_length=1)
    image: constr(min_length=1)
    tag: constr(min_length=1)


class FoodDetectPostResponse(BaseModel):
    annotations: List[Annotation] = Field(..., min_length=0)


class ContentType(Enum):
    application_x_www_form_urlencoded = 'application/x-www-form-urlencoded'
    application_json = 'application/json'
    multipart_form_data = 'multipart/form-data'


class Category(BaseModel):
    name: constr(min_length=1)
    probability: float


class ConfidenceRange95Percent(BaseModel):
    max: float
    min: float


class Calories(BaseModel):
    confidenceRange95Percent: ConfidenceRange95Percent
    standardDeviation: float
    unit: constr(min_length=1)
    value: float


class Carbs(BaseModel):
    confidenceRange95Percent: ConfidenceRange95Percent
    standardDeviation: float
    unit: constr(min_length=1)
    value: float


class Fat(BaseModel):
    confidenceRange95Percent: ConfidenceRange95Percent
    standardDeviation: float
    unit: constr(min_length=1)
    value: float


class Protein(BaseModel):
    confidenceRange95Percent: ConfidenceRange95Percent
    standardDeviation: float
    unit: constr(min_length=1)
    value: float


class Nutrition(BaseModel):
    calories: Calories
    carbs: Carbs
    fat: Fat
    protein: Protein
    recipesUsed: int


class Recipe(BaseModel):
    id: int
    imageType: constr(min_length=1)
    title: constr(min_length=1)
    url: constr(min_length=1)


class FoodImagesAnalyzeGetResponse(BaseModel):
    category: Category
    nutrition: Nutrition
    recipes: List[Recipe] = Field(..., min_length=0)


class FoodImagesClassifyGetResponse(BaseModel):
    category: constr(min_length=1)
    probability: float


class Language(Enum):
    en = 'en'
    de = 'de'


class FoodIngredientsAutocompleteGetResponseItem(BaseModel):
    aisle: Optional[constr(min_length=1)] = None
    id: Optional[int] = None
    image: constr(min_length=1)
    name: constr(min_length=1)
    possibleUnits: Optional[List[str]] = None


class FoodIngredientsAutocompleteGetResponse(
    RootModel[List[FoodIngredientsAutocompleteGetResponseItem]]
):
    root: List[FoodIngredientsAutocompleteGetResponseItem] = Field(
        ..., description='', min_length=0
    )


class FoodIngredientsGlycemicLoadPostRequest(BaseModel):
    ingredients: List[str]


class Ingredient(BaseModel):
    glycemicIndex: float
    glycemicLoad: float
    id: int
    original: constr(min_length=1)


class FoodIngredientsGlycemicLoadPostResponse(BaseModel):
    ingredients: List[Ingredient] = Field(..., min_length=0)
    totalGlycemicLoad: float


class FoodIngredientsMapPostRequest(BaseModel):
    ingredients: List[str]
    servings: float


class Product(BaseModel):
    id: int
    title: constr(min_length=1)
    upc: constr(min_length=1)


class FoodIngredientsMapPostResponseItem(BaseModel):
    ingredientImage: constr(min_length=1)
    meta: List[str]
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    products: List[Product] = Field(..., min_length=0)


class FoodIngredientsMapPostResponse(
    RootModel[List[FoodIngredientsMapPostResponseItem]]
):
    root: List[FoodIngredientsMapPostResponseItem] = Field(
        ..., description='', min_length=0
    )


class Result(BaseModel):
    id: int
    image: constr(min_length=1)
    name: constr(min_length=1)


class FoodIngredientsSearchGetResponse(BaseModel):
    number: int
    offset: int
    results: List[Result] = Field(..., min_length=0)
    totalResults: int


class FoodIngredientsSubstitutesGetResponse(BaseModel):
    ingredient: constr(min_length=1)
    message: constr(min_length=1)
    substitutes: List[str]


class FoodIngredientsIdAmountGetResponse(BaseModel):
    amount: float
    unit: constr(min_length=1)


class EstimatedCost(BaseModel):
    unit: constr(min_length=1)
    value: float


class CaloricBreakdown(BaseModel):
    percentCarbs: float
    percentFat: float
    percentProtein: float


class Nutrient(BaseModel):
    amount: float
    name: constr(min_length=1)
    percentOfDailyNeeds: float
    unit: constr(min_length=1)


class Property(BaseModel):
    amount: float
    name: constr(min_length=1)
    unit: str


class WeightPerServing(BaseModel):
    amount: float
    unit: constr(min_length=1)


class Nutrition1(BaseModel):
    caloricBreakdown: CaloricBreakdown
    nutrients: List[Nutrient] = Field(..., min_length=0)
    properties: List[Property] = Field(..., min_length=0)
    weightPerServing: WeightPerServing


class FoodIngredientsIdInformationGetResponse(BaseModel):
    aisle: constr(min_length=1)
    amount: float
    categoryPath: List[str]
    consistency: constr(min_length=1)
    estimatedCost: EstimatedCost
    id: int
    image: constr(min_length=1)
    meta: List[Dict[str, Any]]
    name: constr(min_length=1)
    nameClean: constr(min_length=1)
    nutrition: Nutrition1
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    possibleUnits: List[str]
    shoppingListUnits: List[str]
    unit: str
    unitLong: str
    unitShort: str


class FoodIngredientsIdSubstitutesGetResponse(BaseModel):
    ingredient: constr(min_length=1)
    message: constr(min_length=1)
    substitutes: List[str]


class FoodJokesRandomGetResponse(BaseModel):
    text: constr(min_length=1)


class AddMenuItemInformation(Enum):
    boolean_False = False
    boolean_True = True


class Servings(BaseModel):
    number: float
    size: float
    unit: constr(min_length=1)


class MenuItem(BaseModel):
    id: int
    image: constr(min_length=1)
    imageType: constr(min_length=1)
    restaurantChain: constr(min_length=1)
    servings: Optional[Servings] = None
    title: constr(min_length=1)


class FoodMenuItemsSearchGetResponse(BaseModel):
    menuItems: List[MenuItem] = Field(..., min_length=0)
    number: int
    offset: int
    totalMenuItems: int
    type: constr(min_length=1)


class Result1(BaseModel):
    id: int
    title: constr(min_length=1)


class FoodMenuItemsSuggestGetResponse(BaseModel):
    results: List[Result1] = Field(..., min_length=0)


class Nutrition2(BaseModel):
    caloricBreakdown: CaloricBreakdown
    nutrients: List[Nutrient] = Field(..., min_length=0)


class FoodMenuItemsIdGetResponse(BaseModel):
    badges: List[str]
    breadcrumbs: List[str]
    generatedText: Optional[str] = None
    id: int
    imageType: constr(min_length=1)
    likes: float
    nutrition: Nutrition2
    price: Optional[float] = None
    restaurantChain: constr(min_length=1)
    servings: Servings
    spoonacularScore: Optional[float] = None
    title: constr(min_length=1)


class Accept(Enum):
    application_json = 'application/json'
    text_html = 'text/html'
    media__ = 'media/*'


class Locale(Enum):
    en_US = 'en_US'
    en_GB = 'en_GB'


class FoodProductsClassifyPostRequest(BaseModel):
    plu_code: str
    title: constr(min_length=1)
    upc: str


class FoodProductsClassifyPostResponse(BaseModel):
    breadcrumbs: List[str]
    category: constr(min_length=1)
    cleanTitle: constr(min_length=1)
    image: constr(min_length=1)
    usdaCode: int


class FoodProductsClassifyBatchPostRequestItem(BaseModel):
    plu_code: str
    title: constr(min_length=1)
    upc: str


class FoodProductsClassifyBatchPostRequest(
    RootModel[List[FoodProductsClassifyBatchPostRequestItem]]
):
    root: List[FoodProductsClassifyBatchPostRequestItem] = Field(
        ..., description='', min_length=0
    )


class FoodProductsClassifyBatchPostResponseItem(BaseModel):
    breadcrumbs: List[str]
    category: constr(min_length=1)
    cleanTitle: constr(min_length=1)
    image: constr(min_length=1)
    usdaCode: int


class FoodProductsClassifyBatchPostResponse(
    RootModel[List[FoodProductsClassifyBatchPostResponseItem]]
):
    root: List[FoodProductsClassifyBatchPostResponseItem] = Field(
        ..., description='', min_length=0
    )


class AddProductInformation(Enum):
    boolean_False = False
    boolean_True = True


class Product1(BaseModel):
    id: int
    imageType: constr(min_length=1)
    title: constr(min_length=1)


class FoodProductsSearchGetResponse(BaseModel):
    number: int
    offset: int
    products: List[Product1] = Field(..., min_length=0)
    totalProducts: int
    type: constr(min_length=1)


class FoodProductsSuggestGetResponse(BaseModel):
    results: List[Result1] = Field(..., min_length=0)


class Ingredient1(BaseModel):
    description: Optional[Any] = None
    name: str
    safety_level: Optional[Any] = None


class Nutrition3(BaseModel):
    caloricBreakdown: CaloricBreakdown
    nutrients: List[Nutrient] = Field(..., min_length=0)


class FoodProductsUpcUpcGetResponse(BaseModel):
    badges: List[str]
    breadcrumbs: List[str]
    generatedText: constr(min_length=1)
    id: int
    imageType: constr(min_length=1)
    importantBadges: List[str]
    ingredientCount: Optional[int] = None
    ingredientList: constr(min_length=1)
    ingredients: List[Ingredient1] = Field(..., min_length=0)
    likes: float
    nutrition: Nutrition3
    price: float
    servings: Servings
    spoonacularScore: float
    title: constr(min_length=1)


class ProteinItem(BaseModel):
    difference: float
    id: int
    image: constr(min_length=1)
    title: constr(min_length=1)


class SpoonacularScoreItem(BaseModel):
    difference: float
    id: int
    image: constr(min_length=1)
    title: constr(min_length=1)


class ComparableProducts(BaseModel):
    calories: List[Dict[str, Any]]
    likes: List[Dict[str, Any]]
    price: List[Dict[str, Any]]
    protein: List[ProteinItem] = Field(..., min_length=0)
    spoonacularScore: List[SpoonacularScoreItem] = Field(..., min_length=0)
    sugar: List[Dict[str, Any]]


class FoodProductsUpcUpcComparableGetResponse(BaseModel):
    comparableProducts: ComparableProducts


class Ingredient2(BaseModel):
    description: Optional[Any] = None
    name: constr(min_length=1)
    safety_level: Optional[Any] = None


class Nutrition4(BaseModel):
    caloricBreakdown: CaloricBreakdown
    nutrients: List[Nutrient] = Field(..., min_length=0)


class FoodProductsIdGetResponse(BaseModel):
    aisle: constr(min_length=1)
    badges: List[str]
    breadcrumbs: List[str]
    generatedText: Optional[Any] = None
    id: int
    imageType: constr(min_length=1)
    importantBadges: List[str]
    ingredientCount: int
    ingredientList: constr(min_length=1)
    ingredients: List[Ingredient2] = Field(..., min_length=0)
    likes: float
    nutrition: Nutrition4
    price: float
    servings: Servings
    spoonacularScore: float
    title: constr(min_length=1)


class Address(BaseModel):
    city: Optional[str] = None
    country: Optional[str] = None
    lat: Optional[float] = None
    latitude: Optional[float] = None
    lon: Optional[float] = None
    longitude: Optional[float] = None
    state: Optional[str] = None
    street_addr: Optional[str] = None
    street_addr_2: Optional[str] = None
    zipcode: Optional[str] = None


class Delivery(BaseModel):
    Friday: Optional[str] = None
    Monday: Optional[str] = None
    Saturday: Optional[str] = None
    Sunday: Optional[str] = None
    Thursday: Optional[str] = None
    Tuesday: Optional[str] = None
    Wednesday: Optional[str] = None


class DineIn(BaseModel):
    Friday: Optional[str] = None
    Monday: Optional[str] = None
    Saturday: Optional[str] = None
    Sunday: Optional[str] = None
    Thursday: Optional[str] = None
    Tuesday: Optional[str] = None
    Wednesday: Optional[str] = None


class Operational(BaseModel):
    Friday: Optional[str] = None
    Monday: Optional[str] = None
    Saturday: Optional[str] = None
    Sunday: Optional[str] = None
    Thursday: Optional[str] = None
    Tuesday: Optional[str] = None
    Wednesday: Optional[str] = None


class Pickup(BaseModel):
    Friday: Optional[str] = None
    Monday: Optional[str] = None
    Saturday: Optional[str] = None
    Sunday: Optional[str] = None
    Thursday: Optional[str] = None
    Tuesday: Optional[str] = None
    Wednesday: Optional[str] = None


class LocalHours(BaseModel):
    delivery: Optional[Delivery] = None
    dine_in: Optional[DineIn] = None
    operational: Optional[Operational] = None
    pickup: Optional[Pickup] = None


class Restaurant(BaseModel):
    field_id: Optional[str] = Field(None, alias='_id')
    address: Optional[Address] = None
    aggregated_rating_count: Optional[int] = None
    cuisines: Optional[List[str]] = None
    delivery_enabled: Optional[bool] = None
    description: Optional[str] = None
    dollar_signs: Optional[int] = None
    food_photos: Optional[List[str]] = None
    is_open: Optional[bool] = None
    local_hours: Optional[LocalHours] = None
    logo_photos: Optional[List[str]] = None
    miles: Optional[float] = None
    name: Optional[str] = None
    offers_first_party_delivery: Optional[bool] = None
    offers_third_party_delivery: Optional[bool] = None
    phone_number: Optional[int] = None
    pickup_enabled: Optional[bool] = None
    store_photos: Optional[List[Dict[str, Any]]] = None
    type: Optional[str] = None
    weighted_rating_value: Optional[float] = None


class FoodRestaurantsSearchGetResponse(BaseModel):
    restaurants: Optional[List[Restaurant]] = None


class Result3(BaseModel):
    content: constr(min_length=0)
    id: str
    image: constr(min_length=1)
    link: constr(min_length=1)
    name: constr(min_length=1)
    relevance: float
    type: constr(min_length=1)


class SearchResult(BaseModel):
    name: constr(min_length=1)
    results: Optional[List[Result3]] = Field(None, min_length=0)
    totalResults: int


class FoodSearchGetResponse(BaseModel):
    limit: int
    offset: int
    query: constr(min_length=1)
    searchResults: List[SearchResult] = Field(..., min_length=0)
    totalResults: int


class Article(BaseModel):
    dataPoints: Optional[List[Dict[str, Any]]] = None
    image: constr(min_length=1)
    link: constr(min_length=1)
    name: constr(min_length=1)


class DataPoint(BaseModel):
    key: constr(min_length=1)
    value: constr(min_length=1)


class GroceryProduct(BaseModel):
    dataPoints: Optional[List[DataPoint]] = Field(None, min_length=0)
    image: constr(min_length=1)
    link: constr(min_length=1)
    name: constr(min_length=1)


class MenuItem1(BaseModel):
    dataPoints: Optional[List[DataPoint]] = Field(None, min_length=0)
    image: constr(min_length=1)
    link: constr(min_length=1)
    name: constr(min_length=1)


class Recipe1(BaseModel):
    dataPoints: Optional[List[DataPoint]] = Field(None, min_length=0)
    image: constr(min_length=1)
    link: constr(min_length=1)
    name: constr(min_length=1)


class FoodSiteSearchGetResponse(BaseModel):
    Articles: List[Article] = Field(..., min_length=0)
    Grocery_Products: List[GroceryProduct] = Field(
        ..., alias='Grocery Products', min_length=0
    )
    Menu_Items: List[MenuItem1] = Field(..., alias='Menu Items', min_length=0)
    Recipes: List[Recipe1] = Field(..., min_length=0)


class FoodTriviaRandomGetResponse(BaseModel):
    text: constr(min_length=1)


class Video(BaseModel):
    length: int
    rating: float
    shortTitle: constr(min_length=1)
    thumbnail: constr(min_length=1)
    title: constr(min_length=1)
    views: int
    youTubeId: constr(min_length=1)


class FoodVideosSearchGetResponse(BaseModel):
    totalResults: int
    videos: List[Video] = Field(..., min_length=0)


class FoodWineDescriptionGetResponse(BaseModel):
    wineDescription: constr(min_length=1)


class FoodWineDishesGetResponse(BaseModel):
    pairings: List[str]
    text: constr(min_length=1)


class ProductMatch(BaseModel):
    averageRating: float
    description: Optional[Any] = None
    id: int
    imageUrl: constr(min_length=1)
    link: constr(min_length=1)
    price: constr(min_length=1)
    ratingCount: int
    score: float
    title: constr(min_length=1)


class FoodWinePairingGetResponse(BaseModel):
    pairedWines: List[str]
    pairingText: constr(min_length=1)
    productMatches: List[ProductMatch] = Field(..., min_length=0)


class RecommendedWine(BaseModel):
    averageRating: float
    description: constr(min_length=1)
    id: int
    imageUrl: constr(min_length=1)
    link: constr(min_length=1)
    price: constr(min_length=1)
    ratingCount: int
    score: float
    title: constr(min_length=1)


class FoodWineRecommendationGetResponse(BaseModel):
    recommendedWines: List[RecommendedWine] = Field(..., min_length=0)
    totalFound: int


class Meal(BaseModel):
    id: int
    imageType: constr(min_length=1)
    readyInMinutes: int
    servings: float
    sourceUrl: constr(min_length=1)
    title: constr(min_length=1)


class Nutrients(BaseModel):
    calories: float
    carbohydrates: float
    fat: float
    protein: float


class MealplannerGenerateGetResponse(BaseModel):
    meals: List[Meal] = Field(..., min_length=0)
    nutrients: Nutrients


class MealplannerUsernameDayDateDeleteRequest(BaseModel):
    date: str = Field(
        ..., description='The date in the format yyyy-mm-dd.', examples=['2020-06-01']
    )
    hash: str = Field(
        ...,
        description='The private hash for the username.',
        examples=['4b5v4398573406'],
    )
    username: str = Field(..., description='The username.', examples=['dsky'])


class MealplannerUsernameDayDateDeleteResponse(BaseModel):
    pass


class MealplannerUsernameItemsPostRequest(BaseModel):
    hash: str = Field(
        ...,
        description='The private hash for the username.',
        examples=['4b5v4398573406'],
    )
    username: str = Field(..., description='The username.', examples=['dsky'])


class Ingredient3(BaseModel):
    name: constr(min_length=1)


class Value(BaseModel):
    ingredients: List[Ingredient3] = Field(..., min_length=0)


class MealplannerUsernameItemsPostRequest1(BaseModel):
    date: float
    position: int
    slot: int
    type: constr(min_length=1)
    value: Value


class MealplannerUsernameItemsPostResponse(BaseModel):
    pass


class MealplannerUsernameItemsIdDeleteRequest(BaseModel):
    hash: str = Field(
        ...,
        description='The private hash for the username.',
        examples=['4b5v4398573406'],
    )
    id: float = Field(..., description='The shopping list item id.', examples=[15678])
    username: str = Field(..., description='The username.', examples=['dsky'])


class MealplannerUsernameItemsIdDeleteResponse(BaseModel):
    pass


class Metric(BaseModel):
    amount: float
    unit: constr(min_length=1)


class Original(BaseModel):
    amount: float
    unit: constr(min_length=1)


class Us(BaseModel):
    amount: float
    unit: constr(min_length=1)


class Measures(BaseModel):
    metric: Metric
    original: Original
    us: Us


class Item(BaseModel):
    aisle: constr(min_length=1)
    cost: float
    id: int
    ingredientId: int
    measures: Optional[Measures] = None
    name: constr(min_length=1)
    pantryItem: bool


class Aisle(BaseModel):
    aisle: constr(min_length=1)
    items: Optional[List[Item]] = Field(None, min_length=0)


class MealplannerUsernameShoppingListGetResponse(BaseModel):
    aisles: List[Aisle] = Field(..., min_length=0)
    cost: float
    endDate: float
    startDate: float


class MealplannerUsernameShoppingListItemsPostRequest(BaseModel):
    hash: str = Field(
        ...,
        description='The private hash for the username.',
        examples=['4b5v4398573406'],
    )
    username: str = Field(..., description='The username.', examples=['dsky'])


class MealplannerUsernameShoppingListItemsPostRequest1(BaseModel):
    aisle: constr(min_length=1)
    item: constr(min_length=1)
    parse: bool


class Measures1(BaseModel):
    metric: Metric
    original: Original
    us: Us


class Item1(BaseModel):
    aisle: constr(min_length=1)
    cost: float
    id: int
    ingredientId: int
    measures: Optional[Measures1] = None
    name: constr(min_length=1)
    pantryItem: bool


class Aisle1(BaseModel):
    aisle: constr(min_length=1)
    items: Optional[List[Item1]] = Field(None, min_length=0)


class MealplannerUsernameShoppingListItemsPostResponse(BaseModel):
    aisles: List[Aisle1] = Field(..., min_length=0)
    cost: float
    endDate: float
    startDate: float


class MealplannerUsernameShoppingListItemsIdDeleteRequest(BaseModel):
    hash: str = Field(
        ...,
        description='The private hash for the username.',
        examples=['4b5v4398573406'],
    )
    id: float = Field(..., description='The shopping list item id.', examples=[15678])
    username: str = Field(..., description='The username.', examples=['dsky'])


class MealplannerUsernameShoppingListItemsIdDeleteResponse(BaseModel):
    pass


class MealplannerUsernameShoppingListStartDateEndDatePostRequest(BaseModel):
    end_date: str = Field(
        ...,
        alias='end-date',
        description='The end date in the format yyyy-mm-dd.',
        examples=['2020-06-07'],
    )
    hash: str = Field(
        ...,
        description='The private hash for the username.',
        examples=['4b5v4398573406'],
    )
    start_date: str = Field(
        ...,
        alias='start-date',
        description='The start date in the format yyyy-mm-dd.',
        examples=['2020-06-01'],
    )
    username: str = Field(..., description='The username.', examples=['dsky'])


class Measures2(BaseModel):
    metric: Metric
    original: Original
    us: Us


class Item2(BaseModel):
    aisle: constr(min_length=1)
    cost: float
    id: int
    ingredientId: int
    measures: Optional[Measures2] = None
    name: constr(min_length=1)
    pantryItem: bool


class Aisle2(BaseModel):
    aisle: constr(min_length=1)
    items: Optional[List[Item2]] = Field(None, min_length=0)


class MealplannerUsernameShoppingListStartDateEndDatePostResponse(BaseModel):
    aisles: List[Aisle2] = Field(..., min_length=0)
    cost: float
    endDate: float
    startDate: float


class Template(BaseModel):
    id: int
    name: constr(min_length=1)


class MealplannerUsernameTemplatesGetResponse(BaseModel):
    templates: List[Template] = Field(..., min_length=0)


class MealplannerUsernameTemplatesPostRequest(BaseModel):
    hash: str = Field(
        ...,
        description='The private hash for the username.',
        examples=['4b5v4398573406'],
    )
    username: str = Field(..., description='The username.', examples=['dsky'])


class Value1(BaseModel):
    id: Optional[int] = None
    imageType: Optional[constr(min_length=1)] = None
    servings: Optional[float] = None
    title: Optional[constr(min_length=1)] = None


class Item3(BaseModel):
    day: int
    position: int
    slot: int
    type: constr(min_length=1)
    value: Optional[Value1] = None


class MealplannerUsernameTemplatesPostResponse(BaseModel):
    items: List[Item3] = Field(..., min_length=1)
    name: constr(min_length=1)
    publishAsPublic: bool


class MealplannerUsernameTemplatesIdDeleteRequest(BaseModel):
    hash: str = Field(
        ...,
        description='The private hash for the username.',
        examples=['4b5v4398573406'],
    )
    id: float = Field(..., description='The shopping list item id.', examples=[15678])
    username: str = Field(..., description='The username.', examples=['dsky'])


class MealplannerUsernameTemplatesIdDeleteResponse(BaseModel):
    pass


class Value2(BaseModel):
    id: float
    imageType: constr(min_length=1)
    title: constr(min_length=1)


class Item4(BaseModel):
    id: int
    position: int
    slot: int
    type: constr(min_length=1)
    value: Optional[Value2] = None


class Nutrient4(BaseModel):
    amount: float
    name: constr(min_length=1)
    percentDailyNeeds: float
    unit: constr(min_length=1)


class NutritionSummary(BaseModel):
    nutrients: List[Nutrient4] = Field(..., min_length=0)


class NutritionSummaryBreakfast(BaseModel):
    nutrients: List[Nutrient4] = Field(..., min_length=0)


class NutritionSummaryDinner(BaseModel):
    nutrients: List[Nutrient4] = Field(..., min_length=0)


class NutritionSummaryLunch(BaseModel):
    nutrients: List[Nutrient4] = Field(..., min_length=0)


class Day(BaseModel):
    day: constr(min_length=1)
    items: Optional[List[Item4]] = Field(None, min_length=0)
    nutritionSummary: Optional[NutritionSummary] = None
    nutritionSummaryBreakfast: Optional[NutritionSummaryBreakfast] = None
    nutritionSummaryDinner: Optional[NutritionSummaryDinner] = None
    nutritionSummaryLunch: Optional[NutritionSummaryLunch] = None


class MealplannerUsernameTemplatesIdGetResponse(BaseModel):
    days: List[Day] = Field(..., min_length=0)
    id: int
    name: constr(min_length=1)


class Value3(BaseModel):
    id: float
    imageType: str
    servings: float
    title: constr(min_length=1)


class Item5(BaseModel):
    id: int
    position: int
    slot: int
    type: constr(min_length=1)
    value: Optional[Value3] = None


class NutritionSummary1(BaseModel):
    nutrients: List[Nutrient4] = Field(..., min_length=0)


class NutritionSummaryBreakfast1(BaseModel):
    nutrients: List[Nutrient4] = Field(..., min_length=0)


class NutritionSummaryDinner1(BaseModel):
    nutrients: List[Nutrient4] = Field(..., min_length=0)


class NutritionSummaryLunch1(BaseModel):
    nutrients: List[Nutrient4] = Field(..., min_length=0)


class Day1(BaseModel):
    date: float
    day: constr(min_length=1)
    items: Optional[List[Item5]] = Field(None, min_length=0)
    nutritionSummary: Optional[NutritionSummary1] = None
    nutritionSummaryBreakfast: Optional[NutritionSummaryBreakfast1] = None
    nutritionSummaryDinner: Optional[NutritionSummaryDinner1] = None
    nutritionSummaryLunch: Optional[NutritionSummaryLunch1] = None


class MealplannerUsernameWeekStartDateGetResponse(BaseModel):
    days: List[Day1] = Field(..., min_length=0)


class RecipesAnalyzePostRequest(BaseModel):
    includeNutrition: Optional[bool] = Field(
        None,
        description='Whether nutrition data should be added to correctly parsed ingredients.',
        examples=[False],
    )
    includeTaste: Optional[bool] = Field(
        None,
        description='Whether taste data should be added to correctly parsed ingredients.',
        examples=[False],
    )
    language: Optional[str] = Field(
        None, description='The input language, either "en" or "de".', examples=['en']
    )


class RecipesAnalyzePostRequest1(BaseModel):
    ingredients: Optional[List[str]] = None
    instructions: Optional[str] = None
    servings: Optional[int] = None
    title: Optional[str] = None


class RecipesAnalyzePostResponse(BaseModel):
    pass


class EquipmentItem(BaseModel):
    id: float
    name: constr(min_length=1)


class Ingredient4(BaseModel):
    id: float
    name: constr(min_length=1)


class EquipmentItem1(BaseModel):
    id: float
    image: constr(min_length=1)
    localizedName: constr(min_length=1)
    name: constr(min_length=1)


class Ingredient5(BaseModel):
    id: float
    image: constr(min_length=1)
    localizedName: constr(min_length=1)
    name: constr(min_length=1)


class Step(BaseModel):
    equipment: Optional[List[EquipmentItem1]] = Field(None, min_length=0)
    ingredients: Optional[List[Ingredient5]] = Field(None, min_length=0)
    number: float
    step: constr(min_length=1)


class ParsedInstruction(BaseModel):
    name: str
    steps: Optional[List[Step]] = Field(None, min_length=0)


class RecipesAnalyzeInstructionsPostResponse(BaseModel):
    equipment: List[EquipmentItem] = Field(..., min_length=0)
    ingredients: List[Ingredient4] = Field(..., min_length=0)
    parsedInstructions: List[ParsedInstruction] = Field(..., min_length=0)


class RecipesAutocompleteGetResponseItem(BaseModel):
    id: int
    imageType: constr(min_length=1)
    title: constr(min_length=1)


class RecipesAutocompleteGetResponse(
    RootModel[List[RecipesAutocompleteGetResponseItem]]
):
    root: List[RecipesAutocompleteGetResponseItem] = Field(
        ..., description='', min_length=0
    )


class Result4(BaseModel):
    calories: float
    carbs: constr(min_length=1)
    fat: constr(min_length=1)
    id: int
    image: constr(min_length=1)
    imageType: constr(min_length=1)
    protein: constr(min_length=1)
    title: constr(min_length=1)


class RecipesComplexSearchGetResponse(BaseModel):
    number: int
    offset: int
    results: List[Result4] = Field(..., min_length=0)
    totalResults: int


class RecipesConvertGetResponse(BaseModel):
    answer: constr(min_length=1)
    sourceAmount: float
    sourceUnit: constr(min_length=1)
    targetAmount: float
    targetUnit: constr(min_length=1)


class RecipesCuisinePostResponse(BaseModel):
    confidence: float
    cuisine: constr(min_length=1)
    cuisines: List[str]


class Metric3(BaseModel):
    amount: float
    unitLong: constr(min_length=0)
    unitShort: constr(min_length=0)


class Us3(BaseModel):
    amount: float
    unitLong: constr(min_length=0)
    unitShort: constr(min_length=0)


class Measures3(BaseModel):
    metric: Metric3
    us: Us3


class ExtendedIngredient(BaseModel):
    aisle: constr(min_length=1)
    amount: float
    consitency: constr(min_length=1)
    id: int
    image: constr(min_length=1)
    measures: Optional[Measures3] = None
    meta: Optional[List[str]] = None
    name: constr(min_length=1)
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    unit: constr(min_length=0)


class ProductMatch1(BaseModel):
    averageRating: float
    description: constr(min_length=1)
    id: int
    imageUrl: constr(min_length=1)
    link: constr(min_length=1)
    price: constr(min_length=1)
    ratingCount: int
    score: float
    title: constr(min_length=1)


class WinePairing(BaseModel):
    pairedWines: List[str]
    pairingText: constr(min_length=1)
    productMatches: List[ProductMatch1] = Field(..., min_length=0)


class RecipesExtractGetResponse(BaseModel):
    aggregateLikes: int
    analyzedInstructions: List[Dict[str, Any]]
    cheap: bool
    creditsText: constr(min_length=1)
    cuisines: List[str]
    dairyFree: bool
    diets: List[str]
    dishTypes: List[str]
    extendedIngredients: List[ExtendedIngredient] = Field(..., min_length=0)
    gaps: constr(min_length=1)
    glutenFree: bool
    healthScore: float
    id: int
    image: constr(min_length=1)
    imageType: constr(min_length=1)
    instructions: str
    ketogenic: bool
    license: constr(min_length=1)
    lowFodmap: bool
    occasions: List[str]
    pricePerServing: float
    readyInMinutes: int
    servings: float
    sourceName: constr(min_length=1)
    sourceUrl: constr(min_length=1)
    spoonacularScore: float
    spoonacularSourceUrl: constr(min_length=1)
    summary: constr(min_length=1)
    sustainable: bool
    title: constr(min_length=1)
    vegan: bool
    vegetarian: bool
    veryHealthy: bool
    veryPopular: bool
    weightWatcherSmartPoints: float
    whole30: bool
    winePairing: WinePairing


class MissedIngredient(BaseModel):
    aisle: constr(min_length=1)
    amount: float
    id: int
    image: constr(min_length=1)
    meta: Optional[List[str]] = None
    name: constr(min_length=1)
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    unit: constr(min_length=0)
    unitLong: constr(min_length=0)
    unitShort: constr(min_length=0)


class UsedIngredient(BaseModel):
    aisle: constr(min_length=1)
    amount: float
    id: int
    image: constr(min_length=1)
    meta: Optional[List[str]] = None
    name: constr(min_length=1)
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    unit: constr(min_length=0)
    unitLong: constr(min_length=0)
    unitShort: constr(min_length=0)


class RecipesFindByIngredientsGetResponseItem(BaseModel):
    id: int
    image: constr(min_length=1)
    imageType: constr(min_length=1)
    likes: int
    missedIngredientCount: int
    missedIngredients: List[MissedIngredient] = Field(..., min_length=0)
    title: constr(min_length=1)
    unusedIngredients: List[Dict[str, Any]] = Field(..., min_length=0)
    usedIngredientCount: float
    usedIngredients: List[UsedIngredient] = Field(..., min_length=0)


class RecipesFindByIngredientsGetResponse(
    RootModel[List[RecipesFindByIngredientsGetResponseItem]]
):
    root: List[RecipesFindByIngredientsGetResponseItem] = Field(
        ..., description='', min_length=0
    )


class RecipesFindByNutrientsGetResponseItem(BaseModel):
    calories: float
    carbs: constr(min_length=1)
    fat: constr(min_length=1)
    id: int
    image: constr(min_length=1)
    imageType: constr(min_length=1)
    protein: constr(min_length=1)
    title: constr(min_length=1)


class RecipesFindByNutrientsGetResponse(
    RootModel[List[RecipesFindByNutrientsGetResponseItem]]
):
    root: List[RecipesFindByNutrientsGetResponseItem] = Field(
        ..., description='', min_length=0
    )


class Calories1(BaseModel):
    confidenceRange95Percent: ConfidenceRange95Percent
    standardDeviation: float
    unit: constr(min_length=1)
    value: float


class Carbs1(BaseModel):
    confidenceRange95Percent: ConfidenceRange95Percent
    standardDeviation: float
    unit: constr(min_length=1)
    value: float


class Fat1(BaseModel):
    confidenceRange95Percent: ConfidenceRange95Percent
    standardDeviation: float
    unit: constr(min_length=1)
    value: float


class Protein1(BaseModel):
    confidenceRange95Percent: ConfidenceRange95Percent
    standardDeviation: float
    unit: constr(min_length=1)
    value: float


class RecipesGuessNutritionGetResponse(BaseModel):
    calories: Calories1
    carbs: Carbs1
    fat: Fat1
    protein: Protein1
    recipesUsed: int


class Measures4(BaseModel):
    metric: Metric3
    us: Us3


class ExtendedIngredient1(BaseModel):
    aisle: constr(min_length=1)
    amount: float
    consitency: constr(min_length=1)
    id: int
    image: constr(min_length=1)
    measures: Optional[Measures4] = None
    meta: Optional[List[str]] = None
    name: constr(min_length=1)
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    unit: constr(min_length=0)


class WinePairing1(BaseModel):
    pairedWines: List[str]
    pairingText: constr(min_length=1)
    productMatches: List[ProductMatch1] = Field(..., min_length=0)


class RecipesInformationBulkGetResponseItem(BaseModel):
    aggregateLikes: int
    analyzedInstructions: List[str]
    cheap: bool
    creditsText: constr(min_length=1)
    cuisines: List[str]
    dairyFree: bool
    diets: List[str]
    dishTypes: List[str]
    extendedIngredients: List[ExtendedIngredient1] = Field(..., min_length=0)
    gaps: constr(min_length=1)
    glutenFree: bool
    healthScore: float
    id: int
    image: constr(min_length=1)
    imageType: constr(min_length=1)
    instructions: str
    ketogenic: bool
    license: constr(min_length=1)
    lowFodmap: bool
    occasions: List[str]
    pricePerServing: float
    readyInMinutes: int
    servings: float
    sourceName: constr(min_length=1)
    sourceUrl: constr(min_length=1)
    spoonacularScore: float
    spoonacularSourceUrl: constr(min_length=1)
    summary: constr(min_length=1)
    sustainable: bool
    title: constr(min_length=1)
    vegan: bool
    vegetarian: bool
    veryHealthy: bool
    veryPopular: bool
    weightWatcherSmartPoints: float
    whole30: bool
    winePairing: WinePairing1


class RecipesInformationBulkGetResponse(
    RootModel[List[RecipesInformationBulkGetResponseItem]]
):
    root: List[RecipesInformationBulkGetResponseItem] = Field(
        ..., description='', min_length=0
    )


class Flavonoid(BaseModel):
    amount: float
    name: constr(min_length=1)
    unit: str


class Nutrient12(BaseModel):
    amount: float
    name: constr(min_length=1)
    percentOfDailyNeeds: float
    unit: constr(min_length=1)


class Nutrition5(BaseModel):
    caloricBreakdown: CaloricBreakdown
    flavonoids: List[Flavonoid] = Field(..., min_length=0)
    nutrients: List[Nutrient12] = Field(..., min_length=0)
    properties: List[Property] = Field(..., min_length=0)
    weightPerServing: WeightPerServing


class RecipesParseIngredientsPostResponseItem(BaseModel):
    aisle: constr(min_length=1)
    amount: float
    consistency: constr(min_length=1)
    estimatedCost: EstimatedCost
    id: int
    image: constr(min_length=1)
    meta: List[str]
    name: constr(min_length=1)
    nameClean: constr(min_length=1)
    nutrition: Nutrition5
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    possibleUnits: List[str]
    unit: constr(min_length=1)
    unitLong: constr(min_length=1)
    unitShort: constr(min_length=1)


class RecipesParseIngredientsPostResponse(
    RootModel[List[RecipesParseIngredientsPostResponseItem]]
):
    root: List[RecipesParseIngredientsPostResponseItem] = Field(
        ..., description='', min_length=0
    )


class Dish(BaseModel):
    image: constr(min_length=1)
    name: constr(min_length=1)


class Ingredient6(BaseModel):
    image: constr(min_length=1)
    include: bool
    name: constr(min_length=1)


class RecipesQueriesAnalyzeGetResponse(BaseModel):
    cuisines: List[str]
    dishes: List[Dish] = Field(..., min_length=0)
    ingredients: List[Ingredient6] = Field(..., min_length=0)
    modifiers: List[str]


class RecipesQuickAnswerGetResponse(BaseModel):
    answer: constr(min_length=1)
    image: constr(min_length=1)


class Measures5(BaseModel):
    metric: Metric3
    us: Us3


class ExtendedIngredient2(BaseModel):
    aisle: constr(min_length=1)
    amount: float
    consitency: constr(min_length=1)
    id: int
    image: constr(min_length=1)
    measures: Optional[Measures5] = None
    meta: Optional[List[str]] = None
    name: constr(min_length=1)
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    unit: constr(min_length=0)


class WinePairing2(BaseModel):
    pairedWines: List[str]
    pairingText: constr(min_length=1)
    productMatches: List[ProductMatch1] = Field(..., min_length=0)


class Recipe2(BaseModel):
    aggregateLikes: float
    analyzedInstructions: Optional[List[Dict[str, Any]]] = None
    cheap: bool
    creditsText: constr(min_length=1)
    cuisines: Optional[List[str]] = None
    dairyFree: bool
    diets: Optional[List[str]] = None
    dishTypes: Optional[List[str]] = None
    extendedIngredients: Optional[List[ExtendedIngredient2]] = Field(None, min_length=0)
    gaps: constr(min_length=1)
    glutenFree: bool
    healthScore: float
    id: int
    image: constr(min_length=1)
    imageType: constr(min_length=1)
    instructions: str
    ketogenic: bool
    license: constr(min_length=1)
    lowFodmap: bool
    occasions: Optional[List[str]] = None
    pricePerServing: float
    readyInMinutes: int
    servings: float
    sourceName: constr(min_length=1)
    sourceUrl: constr(min_length=1)
    spoonacularScore: float
    spoonacularSourceUrl: constr(min_length=1)
    summary: constr(min_length=1)
    sustainable: bool
    title: constr(min_length=1)
    vegan: bool
    vegetarian: bool
    veryHealthy: bool
    veryPopular: bool
    weightWatcherSmartPoints: float
    whole30: bool
    winePairing: Optional[WinePairing2] = None


class RecipesRandomGetResponse(BaseModel):
    recipes: List[Recipe2] = Field(..., min_length=0)


class RecipesVisualizeRecipePostResponse(BaseModel):
    url: constr(min_length=1)


class EquipmentItem2(BaseModel):
    id: int
    name: constr(min_length=1)


class Ingredient7(BaseModel):
    id: int
    name: constr(min_length=1)


class EquipmentItem3(BaseModel):
    id: int
    image: constr(min_length=1)
    localizedName: constr(min_length=1)
    name: constr(min_length=1)


class Ingredient8(BaseModel):
    id: int
    image: constr(min_length=1)
    localizedName: constr(min_length=1)
    name: constr(min_length=1)


class Step1(BaseModel):
    equipment: Optional[List[EquipmentItem3]] = Field(None, min_length=0)
    ingredients: Optional[List[Ingredient8]] = Field(None, min_length=0)
    number: float
    step: constr(min_length=1)


class ParsedInstruction1(BaseModel):
    name: str
    steps: Optional[List[Step1]] = Field(None, min_length=0)


class RecipesIdAnalyzedInstructionsGetResponse(BaseModel):
    equipment: List[EquipmentItem2] = Field(..., min_length=0)
    ingredients: List[Ingredient7] = Field(..., min_length=0)
    parsedInstructions: List[ParsedInstruction1] = Field(..., min_length=0)


class RecipesIdCardGetResponse(BaseModel):
    pass


class Measures6(BaseModel):
    metric: Metric3
    us: Us3


class ExtendedIngredient3(BaseModel):
    aisle: constr(min_length=1)
    amount: float
    consitency: constr(min_length=1)
    id: int
    image: constr(min_length=1)
    measures: Optional[Measures6] = None
    meta: Optional[List[str]] = None
    name: constr(min_length=1)
    original: constr(min_length=1)
    originalName: constr(min_length=1)
    unit: constr(min_length=0)


class WinePairing3(BaseModel):
    pairedWines: List[str]
    pairingText: constr(min_length=1)
    productMatches: List[ProductMatch1] = Field(..., min_length=0)


class RecipesIdInformationGetResponse(BaseModel):
    aggregateLikes: int
    analyzedInstructions: List[Dict[str, Any]]
    cheap: bool
    creditsText: constr(min_length=1)
    cuisines: List[str]
    dairyFree: bool
    diets: List[str]
    dishTypes: List[str]
    extendedIngredients: List[ExtendedIngredient3] = Field(..., min_length=0)
    gaps: constr(min_length=1)
    glutenFree: bool
    healthScore: float
    id: int
    image: constr(min_length=1)
    imageType: constr(min_length=1)
    instructions: str
    ketogenic: bool
    license: constr(min_length=1)
    lowFodmap: bool
    occasions: List[str]
    pricePerServing: float
    readyInMinutes: int
    servings: float
    sourceName: constr(min_length=1)
    sourceUrl: constr(min_length=1)
    spoonacularScore: float
    spoonacularSourceUrl: constr(min_length=1)
    summary: constr(min_length=1)
    sustainable: bool
    title: constr(min_length=1)
    vegan: bool
    vegetarian: bool
    veryHealthy: bool
    veryPopular: bool
    weightWatcherSmartPoints: float
    whole30: bool
    winePairing: WinePairing3


class Measure(Enum):
    us = 'us'
    metric = 'metric'


class RecipesIdSimilarGetResponseItem(BaseModel):
    id: int
    imageType: constr(min_length=1)
    readyInMinutes: int
    servings: float
    sourceUrl: constr(min_length=1)
    title: constr(min_length=1)


class RecipesIdSimilarGetResponse(RootModel[List[RecipesIdSimilarGetResponseItem]]):
    root: List[RecipesIdSimilarGetResponseItem] = Field(
        ..., description='', min_length=0
    )


class RecipesIdSummaryGetResponse(BaseModel):
    id: int
    summary: constr(min_length=1)
    title: constr(min_length=1)


class Normalize(Enum):
    boolean_True = True
    boolean_False = False


class Normalize2(Enum):
    boolean_False = False
    boolean_True = True


class UsersConnectPostRequest(BaseModel):
    pass


class UsersConnectPostRequest1(BaseModel):
    email: constr(min_length=1)
    firstName: constr(min_length=1)
    lastName: constr(min_length=1)
    username: constr(min_length=1)


class UsersConnectPostResponse(BaseModel):
    hash: constr(min_length=1)
    username: constr(min_length=1)
