# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:33:29+00:00

from __future__ import annotations

from pydantic import BaseModel


class PngGetResponse(BaseModel):
    pass
