# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:33:29+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, constr


class EquipmentItem(BaseModel):
    image: constr(min_length=1)
    name: constr(min_length=1)


class JsonGetResponse(BaseModel):
    equipment: List[EquipmentItem] = Field(..., min_length=0)


class PngGetResponse(BaseModel):
    pass
