# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:33:29+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, constr


class BadItem(BaseModel):
    amount: constr(min_length=1)
    indented: bool
    name: constr(min_length=1)
    percentOfDailyNeeds: float


class GoodItem(BaseModel):
    amount: constr(min_length=1)
    indented: bool
    name: constr(min_length=1)
    percentOfDailyNeeds: float


class JsonGetResponse(BaseModel):
    bad: List[BadItem] = Field(..., min_length=0)
    calories: constr(min_length=1)
    carbs: constr(min_length=1)
    fat: constr(min_length=1)
    good: List[GoodItem] = Field(..., min_length=0)
    protein: constr(min_length=1)


class PngGetResponse(BaseModel):
    pass
