# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:33:29+00:00

from __future__ import annotations

from pydantic import BaseModel


class JsonGetResponse(BaseModel):
    bitterness: float
    fattiness: float
    saltiness: float
    savoriness: float
    sourness: float
    spiciness: float
    sweetness: float


class PngGetResponse(BaseModel):
    pass
