# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:33:29+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr


class Metric(BaseModel):
    unit: constr(min_length=0)
    value: float


class Us(BaseModel):
    unit: constr(min_length=0)
    value: float


class Amount(BaseModel):
    metric: Metric
    us: Us


class Ingredient(BaseModel):
    amount: Optional[Amount] = None
    image: constr(min_length=1)
    name: constr(min_length=1)


class JsonGetResponse(BaseModel):
    ingredients: List[Ingredient] = Field(..., min_length=0)


class PngGetResponse(BaseModel):
    pass
