# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:33:29+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Header, Path, Query, UploadFile
from pydantic import confloat, conint
from starlette.requests import Request

from models import (
    Accept,
    AddMenuItemInformation,
    AddProductInformation,
    ContentType,
    FoodConverseGetResponse,
    FoodConverseSuggestGetResponse,
    FoodCustomFoodsSearchGetResponse,
    FoodDetectPostResponse,
    FoodImagesAnalyzeGetResponse,
    FoodImagesClassifyGetResponse,
    FoodIngredientsAutocompleteGetResponse,
    FoodIngredientsGlycemicLoadPostRequest,
    FoodIngredientsGlycemicLoadPostResponse,
    FoodIngredientsIdAmountGetResponse,
    FoodIngredientsIdInformationGetResponse,
    FoodIngredientsIdSubstitutesGetResponse,
    FoodIngredientsMapPostRequest,
    FoodIngredientsMapPostResponse,
    FoodIngredientsSearchGetResponse,
    FoodIngredientsSubstitutesGetResponse,
    FoodJokesRandomGetResponse,
    FoodMenuItemsIdGetResponse,
    FoodMenuItemsSearchGetResponse,
    FoodMenuItemsSuggestGetResponse,
    FoodProductsClassifyBatchPostRequest,
    FoodProductsClassifyBatchPostResponse,
    FoodProductsClassifyPostRequest,
    FoodProductsClassifyPostResponse,
    FoodProductsIdGetResponse,
    FoodProductsSearchGetResponse,
    FoodProductsSuggestGetResponse,
    FoodProductsUpcUpcComparableGetResponse,
    FoodProductsUpcUpcGetResponse,
    FoodRestaurantsSearchGetResponse,
    FoodSearchGetResponse,
    FoodSiteSearchGetResponse,
    FoodTriviaRandomGetResponse,
    FoodVideosSearchGetResponse,
    FoodWineDescriptionGetResponse,
    FoodWineDishesGetResponse,
    FoodWinePairingGetResponse,
    FoodWineRecommendationGetResponse,
    Language,
    Locale,
    MealplannerGenerateGetResponse,
    MealplannerUsernameDayDateDeleteResponse,
    MealplannerUsernameItemsIdDeleteResponse,
    MealplannerUsernameItemsPostRequest1,
    MealplannerUsernameItemsPostResponse,
    MealplannerUsernameShoppingListGetResponse,
    MealplannerUsernameShoppingListItemsIdDeleteResponse,
    MealplannerUsernameShoppingListItemsPostRequest1,
    MealplannerUsernameShoppingListItemsPostResponse,
    MealplannerUsernameShoppingListStartDateEndDatePostResponse,
    MealplannerUsernameTemplatesGetResponse,
    MealplannerUsernameTemplatesIdDeleteResponse,
    MealplannerUsernameTemplatesIdGetResponse,
    MealplannerUsernameTemplatesPostResponse,
    MealplannerUsernameWeekStartDateGetResponse,
    Measure,
    Normalize,
    Normalize2,
    RecipesAnalyzeInstructionsPostResponse,
    RecipesAnalyzePostRequest1,
    RecipesAnalyzePostResponse,
    RecipesAutocompleteGetResponse,
    RecipesComplexSearchGetResponse,
    RecipesConvertGetResponse,
    RecipesCuisinePostResponse,
    RecipesExtractGetResponse,
    RecipesFindByIngredientsGetResponse,
    RecipesFindByNutrientsGetResponse,
    RecipesGuessNutritionGetResponse,
    RecipesIdAnalyzedInstructionsGetResponse,
    RecipesIdCardGetResponse,
    RecipesIdInformationGetResponse,
    RecipesIdSimilarGetResponse,
    RecipesIdSummaryGetResponse,
    RecipesInformationBulkGetResponse,
    RecipesParseIngredientsPostResponse,
    RecipesQueriesAnalyzeGetResponse,
    RecipesQuickAnswerGetResponse,
    RecipesRandomGetResponse,
    RecipesVisualizeRecipePostResponse,
    UsersConnectPostRequest1,
    UsersConnectPostResponse,
)
from models.FoodMenuItems_id_NutritionLabel import PngGetResponse
from models.FoodMenuItems_id_NutritionWidget import PngGetResponse
from models.FoodProducts_id_NutritionLabel import PngGetResponse
from models.FoodProducts_id_NutritionWidget import PngGetResponse
from models.Recipes_id_EquipmentWidget import JsonGetResponse, PngGetResponse
from models.Recipes_id_IngredientWidget import JsonGetResponse, PngGetResponse
from models.Recipes_id_NutritionLabel import PngGetResponse
from models.Recipes_id_NutritionWidget import JsonGetResponse, PngGetResponse
from models.Recipes_id_PriceBreakdownWidget import JsonGetResponse, PngGetResponse
from models.Recipes_id_TasteWidget import JsonGetResponse, PngGetResponse

app = MCPProxy(
    contact={
        'email': 'mail@spoonacular.com',
        'name': 'David Urbansky',
        'url': 'https://spoonacular.com/contact',
    },
    description='The spoonacular Nutrition, Recipe, and Food API allows you to access over thousands of recipes, thousands of ingredients, 800,000 food products, over 100,000 menu items, and restaurants. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as "gluten free brownies without sugar" or "low fat vegan cupcakes." You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what\'s in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.\n\nSpecial diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.',
    license={
        'name': 'spoonacular API Terms',
        'url': 'https://spoonacular.com/food-api/terms',
    },
    termsOfService='https://spoonacular.com/food-api/terms',
    title='spoonacular API',
    version='1.1',
    servers=[{'url': 'https://api.spoonacular.com', 'variables': {}}],
)


@app.get(
    '/food/converse',
    description=""" This endpoint can be used to have a conversation about food with the spoonacular chatbot. Use the "Get Conversation Suggests" endpoint to show your user what he or she can say. """,
    tags=['chatbot_interaction', 'user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def talk_to_chatbot(
    text: str, context_id: Optional[str] = Query(None, alias='contextId')
):
    """
    Talk to Chatbot
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/converse/suggest',
    description=""" This endpoint returns suggestions for things the user can say or ask the chatbot. """,
    tags=['chatbot_interaction', 'user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_conversation_suggests(query: str, number: Optional[float] = None):
    """
    Conversation Suggests
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/customFoods/search',
    description=""" Search custom foods in a user's account. """,
    tags=[
        'ingredient_management',
        'food_content_search',
        'menu_information_management',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_custom_foods(
    query: Optional[str] = None,
    username: str = ...,
    hash: str = ...,
    offset: Optional[conint(ge=0, le=900)] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
):
    """
    Search Custom Foods
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/food/detect',
    description=""" Take any text and find all mentions of food contained within it. This task is also called Named Entity Recognition (NER). In this case, the entities are foods. Either dishes, such as pizza or cheeseburger, or ingredients, such as cucumber or almonds. """,
    tags=['food_detection_analysis', 'food_content_search'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def detect_food_in_text(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    request: Request = ...,
):
    """
    Detect Food in Text
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/images/analyze',
    description=""" Analyze a food image. The API tries to classify the image, guess the nutrition, and find a matching recipes. """,
    tags=[
        'food_detection_analysis',
        'nutrition_information_retrieval',
        'recipe_analysis_tools',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def image_analysis_by_u_r_l(image_url: str = Query(..., alias='imageUrl')):
    """
    Image Analysis by URL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/images/classify',
    description=""" Classify a food image. """,
    tags=[
        'food_detection_analysis',
        'ingredient_management',
        'recipe_classification_tools',
        'recipe_analysis_tools',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def image_classification_by_u_r_l(image_url: str = Query(..., alias='imageUrl')):
    """
    Image Classification by URL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/ingredients/autocomplete',
    description=""" Autocomplete the entry of an ingredient. """,
    tags=['ingredient_management', 'food_content_search'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def autocomplete_ingredient_search(
    query: Optional[str] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
    meta_information: Optional[bool] = Query(None, alias='metaInformation'),
    intolerances: Optional[str] = None,
    language: Optional[Language] = None,
):
    """
    Autocomplete Ingredient Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/food/ingredients/glycemicLoad',
    description=""" Retrieve the glycemic index for a list of ingredients and compute the individual and total glycemic load. """,
    tags=[
        'nutrition_information_retrieval',
        'ingredient_management',
        'food_detection_analysis',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def compute_glycemic_load(
    language: Optional[Language] = None,
    body: FoodIngredientsGlycemicLoadPostRequest = ...,
):
    """
    Compute Glycemic Load
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/food/ingredients/map',
    description=""" Map a set of ingredients to products you can buy in the grocery store. """,
    tags=['ingredient_management', 'grocery_product_information'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def map_ingredients_to_grocery_products(body: FoodIngredientsMapPostRequest):
    """
    Map Ingredients to Grocery Products
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/ingredients/search',
    description=""" Search for simple whole foods (e.g. fruits, vegetables, nuts, grains, meat, fish, dairy etc.). """,
    tags=[
        'ingredient_management',
        'nutrition_information_retrieval',
        'menu_information_management',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def ingredient_search(
    query: Optional[str] = None,
    add_children: Optional[bool] = Query(None, alias='addChildren'),
    min_protein_percent: Optional[float] = Query(None, alias='minProteinPercent'),
    max_protein_percent: Optional[float] = Query(None, alias='maxProteinPercent'),
    min_fat_percent: Optional[float] = Query(None, alias='minFatPercent'),
    max_fat_percent: Optional[float] = Query(None, alias='maxFatPercent'),
    min_carbs_percent: Optional[float] = Query(None, alias='minCarbsPercent'),
    max_carbs_percent: Optional[float] = Query(None, alias='maxCarbsPercent'),
    meta_information: Optional[bool] = Query(None, alias='metaInformation'),
    intolerances: Optional[str] = None,
    sort: Optional[str] = None,
    sort_direction: Optional[str] = Query(None, alias='sortDirection'),
    offset: Optional[conint(ge=0, le=900)] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
    language: Optional[Language] = None,
):
    """
    Ingredient Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/ingredients/substitutes',
    description=""" Search for substitutes for a given ingredient. """,
    tags=['ingredient_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_ingredient_substitutes(
    ingredient_name: str = Query(..., alias='ingredientName')
):
    """
    Get Ingredient Substitutes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/ingredients/{id}/amount',
    description=""" Compute the amount you need of a certain ingredient for a certain nutritional goal. For example, how much pineapple do you have to eat to get 10 grams of protein? """,
    tags=[
        'ingredient_management',
        'ingredient_conversion_tools',
        'nutrition_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def compute_ingredient_amount(
    id: float, nutrient: str = ..., target: float = ..., unit: Optional[str] = None
):
    """
    Compute Ingredient Amount
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/ingredients/{id}/information',
    description=""" Use an ingredient id to get all available information about an ingredient, such as its image and supermarket aisle. """,
    tags=['ingredient_management', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_ingredient_information(
    id: Union[float, int, int, int],
    amount: Optional[float] = None,
    unit: Optional[str] = None,
):
    """
    Get Ingredient Information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/ingredients/{id}/substitutes',
    description=""" Search for substitutes for a given ingredient. """,
    tags=['ingredient_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_ingredient_substitutes_by_i_d(id: Union[float, int, int, int]):
    """
    Get Ingredient Substitutes by ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/jokes/random',
    description=""" Get a random joke that is related to food. Caution: this is an endpoint for adults! """,
    tags=['chatbot_interaction', 'user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_a_random_food_joke():
    """
    Random Food Joke
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/menuItems/search',
    description=""" Search over 115,000 menu items from over 800 fast food and chain restaurants. For example, McDonald's Big Mac or Starbucks Mocha. """,
    tags=[
        'menu_information_management',
        'ingredient_management',
        'nutrition_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_menu_items(
    query: Optional[str] = None,
    min_calories: Optional[float] = Query(None, alias='minCalories'),
    max_calories: Optional[float] = Query(None, alias='maxCalories'),
    min_carbs: Optional[float] = Query(None, alias='minCarbs'),
    max_carbs: Optional[float] = Query(None, alias='maxCarbs'),
    min_protein: Optional[float] = Query(None, alias='minProtein'),
    max_protein: Optional[float] = Query(None, alias='maxProtein'),
    min_fat: Optional[float] = Query(None, alias='minFat'),
    max_fat: Optional[float] = Query(None, alias='maxFat'),
    add_menu_item_information: Optional[AddMenuItemInformation] = Query(
        None, alias='addMenuItemInformation'
    ),
    offset: Optional[conint(ge=0, le=900)] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
):
    """
    Search Menu Items
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/menuItems/suggest',
    description=""" Generate suggestions for menu items based on a (partial) query. The matches will be found by looking in the title only. """,
    tags=['menu_information_management', 'ingredient_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def autocomplete_menu_item_search(
    query: str, number: Optional[confloat(ge=1.0, le=25.0)] = None
):
    """
    Autocomplete Menu Item Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/menuItems/{id}',
    description=""" Use a menu item id to get all available information about a menu item, such as nutrition. """,
    tags=['menu_information_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_menu_item_information(id: Union[float, int, int, int]):
    """
    Get Menu Item Information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/menuItems/{id}/nutritionLabel',
    description=""" Visualize a menu item's nutritional label information as HTML including CSS. """,
    tags=['menu_information_management', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def menu_item_nutrition_label_widget(
    id: Union[float, str, str, str],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
    show_optional_nutrients: Optional[bool] = Query(
        None, alias='showOptionalNutrients'
    ),
    show_zero_values: Optional[bool] = Query(None, alias='showZeroValues'),
    show_ingredients: Optional[bool] = Query(None, alias='showIngredients'),
):
    """
    Menu Item Nutrition Label Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/menuItems/{id}/nutritionLabel.png',
    description=""" Visualize a menu item's nutritional label information as an image. """,
    tags=['menu_information_management', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def menu_item_nutrition_label_image(
    id: Union[float, str, str, str],
    show_optional_nutrients: Optional[bool] = Query(
        None, alias='showOptionalNutrients'
    ),
    show_zero_values: Optional[bool] = Query(None, alias='showZeroValues'),
    show_ingredients: Optional[bool] = Query(None, alias='showIngredients'),
):
    """
    Menu Item Nutrition Label Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/menuItems/{id}/nutritionWidget',
    description=""" Visualize a menu item's nutritional information as HTML including CSS. """,
    tags=['menu_information_management', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_menu_item_nutrition_by_i_d(
    id: Union[float, int, int, int],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
    accept: Optional[Accept] = Header(None, alias='Accept'),
):
    """
    Menu Item Nutrition by ID Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/menuItems/{id}/nutritionWidget.png',
    description=""" Visualize a menu item's nutritional information as HTML including CSS. """,
    tags=['menu_information_management', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def menu_item_nutrition_by_i_d_image(id: Union[float, str, str, str]):
    """
    Menu Item Nutrition by ID Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/food/products/classify',
    description=""" This endpoint allows you to match a packaged food to a basic category, e.g. a specific brand of milk to the category milk. """,
    tags=[
        'grocery_product_information',
        'food_detection_analysis',
        'ingredient_management',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def classify_grocery_product(
    locale: Optional[Locale] = None, body: FoodProductsClassifyPostRequest = ...
):
    """
    Classify Grocery Product
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/food/products/classifyBatch',
    description=""" Provide a set of product jsons, get back classified products. """,
    tags=['grocery_product_information', 'food_detection_analysis'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def classify_grocery_product_bulk(
    locale: Optional[str] = None, body: FoodProductsClassifyBatchPostRequest = ...
):
    """
    Classify Grocery Product Bulk
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/search',
    description=""" Search packaged food products, such as frozen pizza or Greek yogurt. """,
    tags=[
        'grocery_product_information',
        'ingredient_management',
        'nutrition_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_grocery_products(
    query: Optional[str] = None,
    min_calories: Optional[float] = Query(None, alias='minCalories'),
    max_calories: Optional[float] = Query(None, alias='maxCalories'),
    min_carbs: Optional[float] = Query(None, alias='minCarbs'),
    max_carbs: Optional[float] = Query(None, alias='maxCarbs'),
    min_protein: Optional[float] = Query(None, alias='minProtein'),
    max_protein: Optional[float] = Query(None, alias='maxProtein'),
    min_fat: Optional[float] = Query(None, alias='minFat'),
    max_fat: Optional[float] = Query(None, alias='maxFat'),
    add_product_information: Optional[AddProductInformation] = Query(
        None, alias='addProductInformation'
    ),
    offset: Optional[conint(ge=0, le=900)] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
):
    """
    Search Grocery Products
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/suggest',
    description=""" Generate suggestions for grocery products based on a (partial) query. The matches will be found by looking in the title only. """,
    tags=[
        'grocery_product_information',
        'ingredient_management',
        'food_content_search',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def autocomplete_product_search(
    query: str, number: Optional[conint(ge=1, le=25)] = None
):
    """
    Autocomplete Product Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/upc/{upc}',
    description=""" Get information about a packaged food using its UPC. """,
    tags=['grocery_product_information', 'ingredient_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_grocery_products_by_u_p_c(upc: Union[float, str, str, str]):
    """
    Search Grocery Products by UPC
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/upc/{upc}/comparable',
    description=""" Find comparable products to the given one. """,
    tags=['grocery_product_information', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_comparable_products(upc: Union[float, str, str, str]):
    """
    Get Comparable Products
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/{id}',
    description=""" Use a product id to get full information about a product, such as ingredients, nutrition, etc. The nutritional information is per serving. """,
    tags=['grocery_product_information', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_product_information(id: Union[float, int, int, int]):
    """
    Get Product Information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/{id}/nutritionLabel',
    description=""" Get a product's nutrition label as an HTML widget. """,
    tags=[
        'nutrition_information_retrieval',
        'grocery_product_information',
        'ingredient_management',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def product_nutrition_label_widget(
    id: Union[float, str, str, str],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
    show_optional_nutrients: Optional[bool] = Query(
        None, alias='showOptionalNutrients'
    ),
    show_zero_values: Optional[bool] = Query(None, alias='showZeroValues'),
    show_ingredients: Optional[bool] = Query(None, alias='showIngredients'),
):
    """
    Product Nutrition Label Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/{id}/nutritionLabel.png',
    description=""" Get a product's nutrition label as an image. """,
    tags=['nutrition_information_retrieval', 'grocery_product_information'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def product_nutrition_label_image(
    id: Union[float, str, str, str],
    show_optional_nutrients: Optional[bool] = Query(
        None, alias='showOptionalNutrients'
    ),
    show_zero_values: Optional[bool] = Query(None, alias='showZeroValues'),
    show_ingredients: Optional[bool] = Query(None, alias='showIngredients'),
):
    """
    Product Nutrition Label Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/{id}/nutritionWidget',
    description=""" Visualize a product's nutritional information as HTML including CSS. """,
    tags=[
        'nutrition_information_retrieval',
        'menu_information_management',
        'grocery_product_information',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_product_nutrition_by_i_d(
    id: Union[float, int, int, int],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
    accept: Optional[Accept] = Header(None, alias='Accept'),
):
    """
    Product Nutrition by ID Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/products/{id}/nutritionWidget.png',
    description=""" Visualize a product's nutritional information as an image. """,
    tags=['nutrition_information_retrieval', 'grocery_product_information'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def product_nutrition_by_i_d_image(id: Union[float, str, str, str]):
    """
    Product Nutrition by ID Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/restaurants/search',
    description=""" Search through thousands of restaurants (in North America) by location, cuisine, budget, and more. """,
    tags=['food_content_search', 'ingredient_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_restaurants(
    query: Optional[str] = None,
    lat: Optional[float] = None,
    lng: Optional[float] = None,
    distance: Optional[float] = None,
    budget: Optional[float] = None,
    cuisine: Optional[str] = None,
    min_rating: Optional[float] = Query(None, alias='min-rating'),
    is_open: Optional[bool] = Query(None, alias='is-open'),
    sort: Optional[str] = None,
    page: Optional[float] = None,
):
    """
    Search Restaurants
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/search',
    description=""" Search all food content with one call. That includes recipes, grocery products, menu items, simple foods (ingredients), and food videos. """,
    tags=[
        'ingredient_management',
        'food_content_search',
        'menu_information_management',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_all_food(
    query: str,
    offset: Optional[conint(ge=0, le=900)] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
):
    """
    Search All Food
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/site/search',
    description=""" Search spoonacular's site content. You'll be able to find everything that you could also find using the search suggestions on spoonacular.com. This is a suggest API so you can send partial strings as queries. """,
    tags=[
        'food_content_search',
        'recipe_query_functions',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_site_content(query: str):
    """
    Search Site Content
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/trivia/random',
    description=""" Returns random food trivia. """,
    tags=['food_content_search', 'chatbot_interaction'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_random_food_trivia():
    """
    Random Food Trivia
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/videos/search',
    description=""" Find recipe and other food related videos. """,
    tags=['food_content_search', 'ingredient_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_food_videos(
    query: Optional[str] = None,
    type: Optional[str] = None,
    cuisine: Optional[str] = None,
    diet: Optional[str] = None,
    include_ingredients: Optional[str] = Query(None, alias='includeIngredients'),
    exclude_ingredients: Optional[str] = Query(None, alias='excludeIngredients'),
    min_length: Optional[float] = Query(None, alias='minLength'),
    max_length: Optional[float] = Query(None, alias='maxLength'),
    offset: Optional[conint(ge=0, le=900)] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
):
    """
    Search Food Videos
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/wine/description',
    description=""" Get a simple description of a certain wine, e.g. "malbec", "riesling", or "merlot". """,
    tags=['wine_information_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_wine_description(wine: str):
    """
    Wine Description
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/wine/dishes',
    description=""" Find a dish that goes well with a given wine. """,
    tags=['wine_information_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_dish_pairing_for_wine(wine: str):
    """
    Dish Pairing for Wine
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/wine/pairing',
    description=""" Find a wine that goes well with a food. Food can be a dish name ("steak"), an ingredient name ("salmon"), or a cuisine ("italian"). """,
    tags=['wine_information_management', 'food_content_search'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_wine_pairing(
    food: str, max_price: Optional[float] = Query(None, alias='maxPrice')
):
    """
    Wine Pairing
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/food/wine/recommendation',
    description=""" Get a specific wine recommendation (concrete product) for a given wine type, e.g. "merlot". """,
    tags=['wine_information_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_wine_recommendation(
    wine: str,
    max_price: Optional[float] = Query(None, alias='maxPrice'),
    min_rating: Optional[float] = Query(None, alias='minRating'),
    number: Optional[confloat(ge=1.0, le=100.0)] = 10,
):
    """
    Wine Recommendation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/mealplanner/generate',
    description=""" Generate a meal plan with three meals per day (breakfast, lunch, and dinner). """,
    tags=['meal_plan_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def generate_meal_plan(
    time_frame: Optional[str] = Query(None, alias='timeFrame'),
    target_calories: Optional[float] = Query(None, alias='targetCalories'),
    diet: Optional[str] = None,
    exclude: Optional[str] = None,
):
    """
    Generate Meal Plan
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/mealplanner/{username}/day/{date}',
    description=""" Delete all planned items from the user's meal plan for a specific day. """,
    tags=['meal_plan_management', 'user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def clear_meal_plan_day(
    username: Union[str, str, str, str],
    date: Union[str, str, str, str] = ...,
    hash: str = ...,
):
    """
    Clear Meal Plan Day
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/mealplanner/{username}/items',
    description=""" Add an item to the user's meal plan. """,
    tags=['meal_plan_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def add_to_meal_plan(
    username: Union[str, str, str, str],
    hash: str = ...,
    body: MealplannerUsernameItemsPostRequest1 = ...,
):
    """
    Add to Meal Plan
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/mealplanner/{username}/items/{id}',
    description=""" Delete an item from the user's meal plan. """,
    tags=['meal_plan_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def delete_from_meal_plan(
    username: Union[str, str, str, str],
    id: Union[float, int, int, int] = ...,
    hash: str = ...,
):
    """
    Delete from Meal Plan
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/mealplanner/{username}/shopping-list',
    description=""" Get the current shopping list for the given user. """,
    tags=['shopping_list_operations', 'user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_shopping_list(username: Union[str, str, str, str], hash: str = ...):
    """
    Get Shopping List
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/mealplanner/{username}/shopping-list/items',
    description=""" Add an item to the current shopping list of a user. """,
    tags=['shopping_list_operations', 'meal_plan_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def add_to_shopping_list(
    username: Union[str, str, str, str],
    hash: str = ...,
    body: MealplannerUsernameShoppingListItemsPostRequest1 = ...,
):
    """
    Add to Shopping List
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/mealplanner/{username}/shopping-list/items/{id}',
    description=""" Delete an item from the current shopping list of the user. """,
    tags=['shopping_list_operations'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def delete_from_shopping_list(
    username: Union[str, str, str, str],
    id: Union[float, int, int, int] = ...,
    hash: str = ...,
):
    """
    Delete from Shopping List
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/mealplanner/{username}/shopping-list/{start-date}/{end-date}',
    description=""" Generate the shopping list for a user from the meal planner in a given time frame. """,
    tags=['shopping_list_operations'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def generate_shopping_list(
    username: Union[str, str, str, str],
    start_date: Union[str, str, str, str] = Path(..., alias='start-date'),
    end_date: Union[str, str, str, str] = Path(..., alias='end-date'),
    hash: str = ...,
):
    """
    Generate Shopping List
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/mealplanner/{username}/templates',
    description=""" Get meal plan templates from user or public ones. """,
    tags=['meal_plan_management', 'user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_meal_plan_templates(username: Union[str, str, str, str], hash: str = ...):
    """
    Get Meal Plan Templates
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/mealplanner/{username}/templates',
    description=""" Add a meal plan template for a user. """,
    tags=['meal_plan_management', 'user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def add_meal_plan_template(username: Union[str, str, str, str], hash: str = ...):
    """
    Add Meal Plan Template
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/mealplanner/{username}/templates/{id}',
    description=""" Delete a meal plan template for a user. """,
    tags=['meal_plan_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def delete_meal_plan_template(
    username: Union[str, str, str, str],
    id: Union[float, int, int, int] = ...,
    hash: str = ...,
):
    """
    Delete Meal Plan Template
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/mealplanner/{username}/templates/{id}',
    description=""" Get information about a meal plan template. """,
    tags=['meal_plan_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_meal_plan_template(
    username: Union[str, str, str, str],
    id: Union[float, int, int, int] = ...,
    hash: str = ...,
):
    """
    Get Meal Plan Template
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/mealplanner/{username}/week/{start-date}',
    description=""" Retrieve a meal planned week for the given user. The username must be a spoonacular user and the hash must the the user's hash that can be found in his/her account. """,
    tags=['meal_plan_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_meal_plan_week(
    username: Union[str, str, str, str],
    start_date: Union[str, str, str, str] = Path(..., alias='start-date'),
    hash: str = ...,
):
    """
    Get Meal Plan Week
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/analyze',
    description=""" This endpoint allows you to send raw recipe information, such as title, servings, and ingredients, to then see what we compute (badges, diets, nutrition, and more). This is useful if you have your own recipe data and want to enrich it with our semantic analysis. """,
    tags=[
        'recipe_analysis_tools',
        'nutrition_information_retrieval',
        'taste_analysis_tools',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def analyze_recipe(
    language: Optional[str] = None,
    include_nutrition: Optional[bool] = Query(None, alias='includeNutrition'),
    include_taste: Optional[bool] = Query(None, alias='includeTaste'),
    body: RecipesAnalyzePostRequest1 = ...,
):
    """
    Analyze Recipe
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/analyzeInstructions',
    description=""" This endpoint allows you to break down instructions into atomic steps. Furthermore, each step will contain the ingredients and equipment required. Additionally, all ingredients and equipment from the recipe's instructions will be extracted independently of the step they're used in. """,
    tags=[
        'recipe_analysis_tools',
        'nutritional_analysis_tools',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def analyze_recipe_instructions(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    request: Request = ...,
):
    """
    Analyze Recipe Instructions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/autocomplete',
    description=""" Autocomplete a partial input to suggest possible recipe names. """,
    tags=[
        'recipe_query_functions',
        'recipe_information_retrieval',
        'food_content_search',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def autocomplete_recipe_search(
    query: Optional[str] = None, number: Optional[conint(ge=1, le=100)] = 10
):
    """
    Autocomplete Recipe Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/complexSearch',
    description=""" Search through hundreds of thousands of recipes using advanced filtering and ranking. NOTE: This method combines searching by query, by ingredients, and by nutrients into one endpoint. """,
    tags=[
        'recipe_query_functions',
        'recipe_information_retrieval',
        'food_content_search',
        'nutrition_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_recipes(
    query: Optional[str] = None,
    cuisine: Optional[str] = None,
    exclude_cuisine: Optional[str] = Query(None, alias='excludeCuisine'),
    diet: Optional[str] = None,
    intolerances: Optional[str] = None,
    equipment: Optional[str] = None,
    include_ingredients: Optional[str] = Query(None, alias='includeIngredients'),
    exclude_ingredients: Optional[str] = Query(None, alias='excludeIngredients'),
    type: Optional[str] = None,
    instructions_required: Optional[bool] = Query(None, alias='instructionsRequired'),
    fill_ingredients: Optional[bool] = Query(None, alias='fillIngredients'),
    add_recipe_information: Optional[bool] = Query(None, alias='addRecipeInformation'),
    add_recipe_nutrition: Optional[bool] = Query(None, alias='addRecipeNutrition'),
    author: Optional[str] = None,
    tags: Optional[str] = None,
    recipe_box_id: Optional[float] = Query(None, alias='recipeBoxId'),
    title_match: Optional[str] = Query(None, alias='titleMatch'),
    max_ready_time: Optional[float] = Query(None, alias='maxReadyTime'),
    ignore_pantry: Optional[bool] = Query(False, alias='ignorePantry'),
    sort: Optional[str] = None,
    sort_direction: Optional[str] = Query(None, alias='sortDirection'),
    min_carbs: Optional[float] = Query(None, alias='minCarbs'),
    max_carbs: Optional[float] = Query(None, alias='maxCarbs'),
    min_protein: Optional[float] = Query(None, alias='minProtein'),
    max_protein: Optional[float] = Query(None, alias='maxProtein'),
    min_calories: Optional[float] = Query(None, alias='minCalories'),
    max_calories: Optional[float] = Query(None, alias='maxCalories'),
    min_fat: Optional[float] = Query(None, alias='minFat'),
    max_fat: Optional[float] = Query(None, alias='maxFat'),
    min_alcohol: Optional[float] = Query(None, alias='minAlcohol'),
    max_alcohol: Optional[float] = Query(None, alias='maxAlcohol'),
    min_caffeine: Optional[float] = Query(None, alias='minCaffeine'),
    max_caffeine: Optional[float] = Query(None, alias='maxCaffeine'),
    min_copper: Optional[float] = Query(None, alias='minCopper'),
    max_copper: Optional[float] = Query(None, alias='maxCopper'),
    min_calcium: Optional[float] = Query(None, alias='minCalcium'),
    max_calcium: Optional[float] = Query(None, alias='maxCalcium'),
    min_choline: Optional[float] = Query(None, alias='minCholine'),
    max_choline: Optional[float] = Query(None, alias='maxCholine'),
    min_cholesterol: Optional[float] = Query(None, alias='minCholesterol'),
    max_cholesterol: Optional[float] = Query(None, alias='maxCholesterol'),
    min_fluoride: Optional[float] = Query(None, alias='minFluoride'),
    max_fluoride: Optional[float] = Query(None, alias='maxFluoride'),
    min_saturated_fat: Optional[float] = Query(None, alias='minSaturatedFat'),
    max_saturated_fat: Optional[float] = Query(None, alias='maxSaturatedFat'),
    min_vitamin_a: Optional[float] = Query(None, alias='minVitaminA'),
    max_vitamin_a: Optional[float] = Query(None, alias='maxVitaminA'),
    min_vitamin_c: Optional[float] = Query(None, alias='minVitaminC'),
    max_vitamin_c: Optional[float] = Query(None, alias='maxVitaminC'),
    min_vitamin_d: Optional[float] = Query(None, alias='minVitaminD'),
    max_vitamin_d: Optional[float] = Query(None, alias='maxVitaminD'),
    min_vitamin_e: Optional[float] = Query(None, alias='minVitaminE'),
    max_vitamin_e: Optional[float] = Query(None, alias='maxVitaminE'),
    min_vitamin_k: Optional[float] = Query(None, alias='minVitaminK'),
    max_vitamin_k: Optional[float] = Query(None, alias='maxVitaminK'),
    min_vitamin_b1: Optional[float] = Query(None, alias='minVitaminB1'),
    max_vitamin_b1: Optional[float] = Query(None, alias='maxVitaminB1'),
    min_vitamin_b2: Optional[float] = Query(None, alias='minVitaminB2'),
    max_vitamin_b2: Optional[float] = Query(None, alias='maxVitaminB2'),
    min_vitamin_b5: Optional[float] = Query(None, alias='minVitaminB5'),
    max_vitamin_b5: Optional[float] = Query(None, alias='maxVitaminB5'),
    min_vitamin_b3: Optional[float] = Query(None, alias='minVitaminB3'),
    max_vitamin_b3: Optional[float] = Query(None, alias='maxVitaminB3'),
    min_vitamin_b6: Optional[float] = Query(None, alias='minVitaminB6'),
    max_vitamin_b6: Optional[float] = Query(None, alias='maxVitaminB6'),
    min_vitamin_b12: Optional[float] = Query(None, alias='minVitaminB12'),
    max_vitamin_b12: Optional[float] = Query(None, alias='maxVitaminB12'),
    min_fiber: Optional[float] = Query(None, alias='minFiber'),
    max_fiber: Optional[float] = Query(None, alias='maxFiber'),
    min_folate: Optional[float] = Query(None, alias='minFolate'),
    max_folate: Optional[float] = Query(None, alias='maxFolate'),
    min_folic_acid: Optional[float] = Query(None, alias='minFolicAcid'),
    max_folic_acid: Optional[float] = Query(None, alias='maxFolicAcid'),
    min_iodine: Optional[float] = Query(None, alias='minIodine'),
    max_iodine: Optional[float] = Query(None, alias='maxIodine'),
    min_iron: Optional[float] = Query(None, alias='minIron'),
    max_iron: Optional[float] = Query(None, alias='maxIron'),
    min_magnesium: Optional[float] = Query(None, alias='minMagnesium'),
    max_magnesium: Optional[float] = Query(None, alias='maxMagnesium'),
    min_manganese: Optional[float] = Query(None, alias='minManganese'),
    max_manganese: Optional[float] = Query(None, alias='maxManganese'),
    min_phosphorus: Optional[float] = Query(None, alias='minPhosphorus'),
    max_phosphorus: Optional[float] = Query(None, alias='maxPhosphorus'),
    min_potassium: Optional[float] = Query(None, alias='minPotassium'),
    max_potassium: Optional[float] = Query(None, alias='maxPotassium'),
    min_selenium: Optional[float] = Query(None, alias='minSelenium'),
    max_selenium: Optional[float] = Query(None, alias='maxSelenium'),
    min_sodium: Optional[float] = Query(None, alias='minSodium'),
    max_sodium: Optional[float] = Query(None, alias='maxSodium'),
    min_sugar: Optional[float] = Query(None, alias='minSugar'),
    max_sugar: Optional[float] = Query(None, alias='maxSugar'),
    min_zinc: Optional[float] = Query(None, alias='minZinc'),
    max_zinc: Optional[float] = Query(None, alias='maxZinc'),
    offset: Optional[conint(ge=0, le=900)] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
    limit_license: Optional[bool] = Query(True, alias='limitLicense'),
):
    """
    Search Recipes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/convert',
    description=""" Convert amounts like "2 cups of flour to grams". """,
    tags=['ingredient_management', 'ingredient_conversion_tools'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def convert_amounts(
    ingredient_name: str = Query(..., alias='ingredientName'),
    source_amount: float = Query(..., alias='sourceAmount'),
    source_unit: str = Query(..., alias='sourceUnit'),
    target_unit: str = Query(..., alias='targetUnit'),
):
    """
    Convert Amounts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/cuisine',
    description=""" Classify the recipe's cuisine. """,
    tags=['food_detection_analysis', 'recipe_classification_tools'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def classify_cuisine(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    request: Request = ...,
):
    """
    Classify Cuisine
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/extract',
    description=""" This endpoint lets you extract recipe data such as title, ingredients, and instructions from any properly formatted Website. """,
    tags=[
        'recipe_extraction_tools',
        'recipe_information_retrieval',
        'food_content_search',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def extract_recipe_from_website(
    url: str,
    force_extraction: Optional[bool] = Query(None, alias='forceExtraction'),
    analyze: Optional[bool] = None,
    include_nutrition: Optional[bool] = Query(False, alias='includeNutrition'),
    include_taste: Optional[bool] = Query(False, alias='includeTaste'),
):
    """
    Extract Recipe from Website
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/findByIngredients',
    description=""" 
Ever wondered what recipes you can cook with the ingredients you have in your fridge or pantry? This endpoint lets you find recipes that either maximize the usage of ingredients you have at hand (pre shopping) or minimize the ingredients that you don't currently have (post shopping).
         """,
    tags=['ingredient_management', 'recipe_query_functions', 'food_content_search'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_recipes_by_ingredients(
    ingredients: Optional[str] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
    limit_license: Optional[bool] = Query(True, alias='limitLicense'),
    ranking: Optional[float] = None,
    ignore_pantry: Optional[bool] = Query(False, alias='ignorePantry'),
):
    """
    Search Recipes by Ingredients
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/findByNutrients',
    description=""" Find a set of recipes that adhere to the given nutritional limits. You may set limits for macronutrients (calories, protein, fat, and carbohydrate) and/or many micronutrients. """,
    tags=[
        'menu_information_management',
        'recipe_query_functions',
        'nutrition_information_retrieval',
        'nutritional_analysis_tools',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def search_recipes_by_nutrients(
    min_carbs: Optional[float] = Query(None, alias='minCarbs'),
    max_carbs: Optional[float] = Query(None, alias='maxCarbs'),
    min_protein: Optional[float] = Query(None, alias='minProtein'),
    max_protein: Optional[float] = Query(None, alias='maxProtein'),
    min_calories: Optional[float] = Query(None, alias='minCalories'),
    max_calories: Optional[float] = Query(None, alias='maxCalories'),
    min_fat: Optional[float] = Query(None, alias='minFat'),
    max_fat: Optional[float] = Query(None, alias='maxFat'),
    min_alcohol: Optional[float] = Query(None, alias='minAlcohol'),
    max_alcohol: Optional[float] = Query(None, alias='maxAlcohol'),
    min_caffeine: Optional[float] = Query(None, alias='minCaffeine'),
    max_caffeine: Optional[float] = Query(None, alias='maxCaffeine'),
    min_copper: Optional[float] = Query(None, alias='minCopper'),
    max_copper: Optional[float] = Query(None, alias='maxCopper'),
    min_calcium: Optional[float] = Query(None, alias='minCalcium'),
    max_calcium: Optional[float] = Query(None, alias='maxCalcium'),
    min_choline: Optional[float] = Query(None, alias='minCholine'),
    max_choline: Optional[float] = Query(None, alias='maxCholine'),
    min_cholesterol: Optional[float] = Query(None, alias='minCholesterol'),
    max_cholesterol: Optional[float] = Query(None, alias='maxCholesterol'),
    min_fluoride: Optional[float] = Query(None, alias='minFluoride'),
    max_fluoride: Optional[float] = Query(None, alias='maxFluoride'),
    min_saturated_fat: Optional[float] = Query(None, alias='minSaturatedFat'),
    max_saturated_fat: Optional[float] = Query(None, alias='maxSaturatedFat'),
    min_vitamin_a: Optional[float] = Query(None, alias='minVitaminA'),
    max_vitamin_a: Optional[float] = Query(None, alias='maxVitaminA'),
    min_vitamin_c: Optional[float] = Query(None, alias='minVitaminC'),
    max_vitamin_c: Optional[float] = Query(None, alias='maxVitaminC'),
    min_vitamin_d: Optional[float] = Query(None, alias='minVitaminD'),
    max_vitamin_d: Optional[float] = Query(None, alias='maxVitaminD'),
    min_vitamin_e: Optional[float] = Query(None, alias='minVitaminE'),
    max_vitamin_e: Optional[float] = Query(None, alias='maxVitaminE'),
    min_vitamin_k: Optional[float] = Query(None, alias='minVitaminK'),
    max_vitamin_k: Optional[float] = Query(None, alias='maxVitaminK'),
    min_vitamin_b1: Optional[float] = Query(None, alias='minVitaminB1'),
    max_vitamin_b1: Optional[float] = Query(None, alias='maxVitaminB1'),
    min_vitamin_b2: Optional[float] = Query(None, alias='minVitaminB2'),
    max_vitamin_b2: Optional[float] = Query(None, alias='maxVitaminB2'),
    min_vitamin_b5: Optional[float] = Query(None, alias='minVitaminB5'),
    max_vitamin_b5: Optional[float] = Query(None, alias='maxVitaminB5'),
    min_vitamin_b3: Optional[float] = Query(None, alias='minVitaminB3'),
    max_vitamin_b3: Optional[float] = Query(None, alias='maxVitaminB3'),
    min_vitamin_b6: Optional[float] = Query(None, alias='minVitaminB6'),
    max_vitamin_b6: Optional[float] = Query(None, alias='maxVitaminB6'),
    min_vitamin_b12: Optional[float] = Query(None, alias='minVitaminB12'),
    max_vitamin_b12: Optional[float] = Query(None, alias='maxVitaminB12'),
    min_fiber: Optional[float] = Query(None, alias='minFiber'),
    max_fiber: Optional[float] = Query(None, alias='maxFiber'),
    min_folate: Optional[float] = Query(None, alias='minFolate'),
    max_folate: Optional[float] = Query(None, alias='maxFolate'),
    min_folic_acid: Optional[float] = Query(None, alias='minFolicAcid'),
    max_folic_acid: Optional[float] = Query(None, alias='maxFolicAcid'),
    min_iodine: Optional[float] = Query(None, alias='minIodine'),
    max_iodine: Optional[float] = Query(None, alias='maxIodine'),
    min_iron: Optional[float] = Query(None, alias='minIron'),
    max_iron: Optional[float] = Query(None, alias='maxIron'),
    min_magnesium: Optional[float] = Query(None, alias='minMagnesium'),
    max_magnesium: Optional[float] = Query(None, alias='maxMagnesium'),
    min_manganese: Optional[float] = Query(None, alias='minManganese'),
    max_manganese: Optional[float] = Query(None, alias='maxManganese'),
    min_phosphorus: Optional[float] = Query(None, alias='minPhosphorus'),
    max_phosphorus: Optional[float] = Query(None, alias='maxPhosphorus'),
    min_potassium: Optional[float] = Query(None, alias='minPotassium'),
    max_potassium: Optional[float] = Query(None, alias='maxPotassium'),
    min_selenium: Optional[float] = Query(None, alias='minSelenium'),
    max_selenium: Optional[float] = Query(None, alias='maxSelenium'),
    min_sodium: Optional[float] = Query(None, alias='minSodium'),
    max_sodium: Optional[float] = Query(None, alias='maxSodium'),
    min_sugar: Optional[float] = Query(None, alias='minSugar'),
    max_sugar: Optional[float] = Query(None, alias='maxSugar'),
    min_zinc: Optional[float] = Query(None, alias='minZinc'),
    max_zinc: Optional[float] = Query(None, alias='maxZinc'),
    offset: Optional[conint(ge=0, le=900)] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
    random: Optional[bool] = None,
    limit_license: Optional[bool] = Query(True, alias='limitLicense'),
):
    """
    Search Recipes by Nutrients
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/guessNutrition',
    description=""" Estimate the macronutrients of a dish based on its title. """,
    tags=[
        'nutrition_information_retrieval',
        'recipe_classification_tools',
        'menu_information_management',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def guess_nutrition_by_dish_name(title: str):
    """
    Guess Nutrition by Dish Name
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/informationBulk',
    description=""" Get information about multiple recipes at once. This is equivalent to calling the Get Recipe Information endpoint multiple times, but faster. """,
    tags=[
        'recipe_information_retrieval',
        'food_content_search',
        'nutrition_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_recipe_information_bulk(
    ids: str, include_nutrition: Optional[bool] = Query(False, alias='includeNutrition')
):
    """
    Get Recipe Information Bulk
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/parseIngredients',
    description=""" Extract an ingredient from plain text. """,
    tags=[
        'ingredient_management',
        'ingredient_visualization_tools',
        'recipe_analysis_tools',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def parse_ingredients(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    language: Optional[Language] = None,
    request: Request = ...,
):
    """
    Parse Ingredients
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/queries/analyze',
    description=""" Parse a recipe search query to find out its intention. """,
    tags=[
        'recipe_query_functions',
        'recipe_information_retrieval',
        'recipe_extraction_tools',
        'food_content_search',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def analyze_a_recipe_search_query(q: str):
    """
    Analyze a Recipe Search Query
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/quickAnswer',
    description=""" Answer a nutrition related natural language question. """,
    tags=['chatbot_interaction', 'user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def quick_answer(q: str):
    """
    Quick Answer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/random',
    description=""" Find random (popular) recipes. If you need to filter recipes by diet, nutrition etc. you might want to consider using the complex recipe search endpoint and set the sort request parameter to random. """,
    tags=[
        'food_content_search',
        'recipe_information_retrieval',
        'recipe_query_functions',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_random_recipes(
    limit_license: Optional[bool] = Query(True, alias='limitLicense'),
    tags: Optional[str] = None,
    number: Optional[conint(ge=1, le=100)] = 10,
):
    """
    Get Random Recipes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/visualizeEquipment',
    description=""" Visualize the equipment used to make a recipe. """,
    tags=['cooking_equipment_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_equipment(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    accept: Optional[Accept] = Header(None, alias='Accept'),
    request: Request = ...,
):
    """
    Equipment Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/visualizeIngredients',
    description=""" Visualize ingredients of a recipe. You can play around with that endpoint! """,
    tags=['ingredient_management', 'food_detection_analysis'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_ingredients(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    language: Optional[Language] = None,
    accept: Optional[Accept] = Header(None, alias='Accept'),
    request: Request = ...,
):
    """
    Ingredients Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/visualizeNutrition',
    description=""" Visualize a recipe's nutritional information as HTML including CSS. """,
    tags=[
        'nutrition_information_retrieval',
        'recipe_analysis_tools',
        'recipe_information_retrieval',
        'recipe_visualization_tools',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_recipe_nutrition(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    accept: Optional[Accept] = Header(None, alias='Accept'),
    language: Optional[Language] = None,
    request: Request = ...,
):
    """
    Recipe Nutrition Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/visualizePriceEstimator',
    description=""" Visualize the price breakdown of a recipe. """,
    tags=['recipe_cost_analysis', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_price_breakdown(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    accept: Optional[Accept] = Header(None, alias='Accept'),
    language: Optional[Language] = None,
    request: Request = ...,
):
    """
    Price Breakdown Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/visualizeRecipe',
    description=""" Generate a recipe card for a recipe. """,
    tags=['recipe_card_creation'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def create_recipe_card(
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    file: UploadFile = ...,
):
    """
    Create Recipe Card
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/recipes/visualizeTaste',
    description=""" Visualize a recipe's taste information as HTML including CSS. You can play around with that endpoint! """,
    tags=['recipe_analysis_tools', 'taste_analysis_tools'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_recipe_taste(
    language: Optional[Language] = None,
    content__type: Optional[ContentType] = Header(None, alias='Content-Type'),
    accept: Optional[Accept] = Header(None, alias='Accept'),
    normalize: Optional[bool] = None,
    rgb: Optional[str] = None,
    request: Request = ...,
):
    """
    Recipe Taste Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/analyzedInstructions',
    description=""" Get an analyzed breakdown of a recipe's instructions. Each step is enriched with the ingredients and equipment required. """,
    tags=['recipe_analysis_tools', 'recipe_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_analyzed_recipe_instructions(
    id: Union[float, int, int, int],
    step_breakdown: Optional[bool] = Query(None, alias='stepBreakdown'),
):
    """
    Get Analyzed Recipe Instructions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/card',
    description=""" Generate a recipe card for a recipe. """,
    tags=['recipe_card_creation'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def create_recipe_card_get(
    id: float,
    mask: Optional[str] = None,
    background_image: Optional[str] = Query(None, alias='backgroundImage'),
    background_color: Optional[str] = Query(None, alias='backgroundColor'),
    font_color: Optional[str] = Query(None, alias='fontColor'),
):
    """
    Create Recipe Card
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/equipmentWidget',
    description=""" Visualize a recipe's equipment list. """,
    tags=['cooking_equipment_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_recipe_equipment_by_i_d(
    id: Union[float, int, int, int],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
):
    """
    Equipment by ID Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/equipmentWidget.json',
    description=""" Get a recipe's equipment list. """,
    tags=['cooking_equipment_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_recipe_equipment_by_i_d(id: Union[float, int, int, int]):
    """
    Equipment by ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/equipmentWidget.png',
    description=""" Visualize a recipe's equipment list as an image. """,
    tags=['cooking_equipment_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def equipment_by_i_d_image(id: Union[float, str, str, str]):
    """
    Equipment by ID Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/information',
    description=""" Use a recipe id to get full information about a recipe, such as ingredients, nutrition, diet and allergen information, etc. """,
    tags=[
        'recipe_information_retrieval',
        'nutrition_information_retrieval',
        'recipe_query_functions',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_recipe_information(
    id: Union[float, int, int, int],
    include_nutrition: Optional[bool] = Query(False, alias='includeNutrition'),
):
    """
    Get Recipe Information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/ingredientWidget',
    description=""" Visualize a recipe's ingredient list. """,
    tags=[
        'ingredient_management',
        'menu_information_management',
        'nutrition_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_recipe_ingredients_by_i_d(
    id: Union[float, int, int, int],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
    measure: Optional[Measure] = None,
):
    """
    Ingredients by ID Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/ingredientWidget.json',
    description=""" Get a recipe's ingredient list. """,
    tags=['ingredient_management', 'recipe_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_recipe_ingredients_by_i_d(id: Union[float, int, int, int]):
    """
    Ingredients by ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/ingredientWidget.png',
    description=""" Visualize a recipe's ingredient list. """,
    tags=[
        'ingredient_management',
        'ingredient_visualization_tools',
        'nutrition_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def ingredients_by_i_d_image(
    id: Union[float, str, str, str], measure: Optional[Measure] = None
):
    """
    Ingredients by ID Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/nutritionLabel',
    description=""" Get a recipe's nutrition label as an HTML widget. """,
    tags=[
        'nutrition_information_retrieval',
        'recipe_visualization_tools',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def recipe_nutrition_label_widget(
    id: Union[float, str, str, str],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
    show_optional_nutrients: Optional[bool] = Query(
        None, alias='showOptionalNutrients'
    ),
    show_zero_values: Optional[bool] = Query(None, alias='showZeroValues'),
    show_ingredients: Optional[bool] = Query(None, alias='showIngredients'),
):
    """
    Recipe Nutrition Label Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/nutritionLabel.png',
    description=""" Get a recipe's nutrition label as an image. """,
    tags=[
        'nutrition_information_retrieval',
        'recipe_visualization_tools',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def recipe_nutrition_label_image(
    id: Union[float, str, str, str],
    show_optional_nutrients: Optional[bool] = Query(
        None, alias='showOptionalNutrients'
    ),
    show_zero_values: Optional[bool] = Query(None, alias='showZeroValues'),
    show_ingredients: Optional[bool] = Query(None, alias='showIngredients'),
):
    """
    Recipe Nutrition Label Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/nutritionWidget',
    description=""" Visualize a recipe's nutritional information as HTML including CSS. """,
    tags=[
        'nutrition_information_retrieval',
        'recipe_information_retrieval',
        'recipe_analysis_tools',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_recipe_nutrition_by_i_d(
    id: Union[float, int, int, int],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
    accept: Optional[Accept] = Header(None, alias='Accept'),
):
    """
    Recipe Nutrition by ID Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/nutritionWidget.json',
    description=""" Get a recipe's nutrition data. """,
    tags=[
        'nutrition_information_retrieval',
        'menu_information_management',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_recipe_nutrition_widget_by_i_d(id: Union[float, int, int, int]):
    """
    Nutrition by ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/nutritionWidget.png',
    description=""" Visualize a recipe's nutritional information as an image. """,
    tags=[
        'nutrition_information_retrieval',
        'recipe_information_retrieval',
        'recipe_analysis_tools',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def recipe_nutrition_by_i_d_image(id: Union[float, str, str, str]):
    """
    Recipe Nutrition by ID Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/priceBreakdownWidget',
    description=""" Visualize a recipe's price breakdown. """,
    tags=['recipe_cost_analysis', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_recipe_price_breakdown_by_i_d(
    id: Union[float, int, int, int],
    default_css: Optional[bool] = Query(True, alias='defaultCss'),
):
    """
    Price Breakdown by ID Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/priceBreakdownWidget.json',
    description=""" Get a recipe's price breakdown data. """,
    tags=['recipe_cost_analysis'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_recipe_price_breakdown_by_i_d(id: Union[float, int, int, int]):
    """
    Price Breakdown by ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/priceBreakdownWidget.png',
    description=""" Visualize a recipe's price breakdown. """,
    tags=['recipe_cost_analysis', 'nutrition_information_retrieval'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def price_breakdown_by_i_d_image(id: Union[float, str, str, str]):
    """
    Price Breakdown by ID Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/similar',
    description=""" Find recipes which are similar to the given one. """,
    tags=[
        'recipe_discovery_suggestions',
        'food_content_search',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_similar_recipes(
    id: Union[float, int, int, int],
    number: Optional[conint(ge=1, le=100)] = 10,
    limit_license: Optional[bool] = Query(True, alias='limitLicense'),
):
    """
    Get Similar Recipes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/summary',
    description=""" Automatically generate a short description that summarizes key information about the recipe. """,
    tags=[
        'recipe_information_retrieval',
        'recipe_analysis_tools',
        'recipe_visualization_tools',
        'recipe_discovery_suggestions',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def summarize_recipe(id: Union[float, int, int, int]):
    """
    Summarize Recipe
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/tasteWidget',
    description=""" Get a recipe's taste. The tastes supported are sweet, salty, sour, bitter, savory, and fatty. """,
    tags=[
        'recipe_analysis_tools',
        'taste_analysis_tools',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def visualize_recipe_taste_by_i_d(
    id: Union[float, int, int, int],
    normalize: Optional[Normalize] = True,
    rgb: Optional[str] = None,
):
    """
    Recipe Taste by ID Widget
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/tasteWidget.json',
    description=""" Get a recipe's taste. The tastes supported are sweet, salty, sour, bitter, savory, and fatty. """,
    tags=['taste_analysis_tools', 'recipe_discovery_suggestions'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def get_recipe_taste_by_i_d(
    id: Union[float, int, int, int], normalize: Optional[Normalize2] = True
):
    """
    Taste by ID
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/recipes/{id}/tasteWidget.png',
    description=""" Get a recipe's taste as an image. The tastes supported are sweet, salty, sour, bitter, savory, and fatty. """,
    tags=[
        'taste_analysis_tools',
        'recipe_analysis_tools',
        'recipe_information_retrieval',
    ],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def recipe_taste_by_i_d_image(
    id: Union[float, str, str, str],
    normalize: Optional[bool] = None,
    rgb: Optional[str] = None,
):
    """
    Recipe Taste by ID Image
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/users/connect',
    description=""" In order to call user-specific endpoints, you need to connect your app's users to spoonacular users. """,
    tags=['user_interaction_management'],
    security=[
        APIKeyHeader(name="x-api-key"),
    ],
)
def connect_user(body: UsersConnectPostRequest1):
    """
    Connect User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
